;                                           (convert_to_metta_file  done_so_convert_tok_split_3 $_933980 tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_tok_split_3.pl tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_tok_split_3.metta)

  !(encoding iso-latin-1)
  !(dynamic (with_self  (pllm *) (/ tok-split 3)))
  !(multifile (with_self  (pllm *) (/ tok-split 3)))
  !(module-transparent (with_self  (pllm *) (/ tok-split 3)))


  !(dynamic (with_self  (so-convert *) (/ tok-split 3)))
  !(multifile (with_self  (so-convert *) (/ tok-split 3)))
  !(module-transparent (with_self  (so-convert *) (/ tok-split 3)))



