;                                           (convert_to_metta_file  done_tmp_buffer_training_2 $_863342 tests/performance/gpt2-like/corpus/tmpdata/done_tmp_buffer_training_2.pl tests/performance/gpt2-like/corpus/tmpdata/done_tmp_buffer_training_2.metta)
  !(encoding iso-latin-1)
;
; Unhandled exception: must_sanity:e(error(existence_error(procedure,pllm:(buffer_training/2)),context(toplevel,DWIM could not correct goal)),pllm:save_training0)porter_stem:tokenize_atom/2: Type error: `character_code' expected, found `No' (an atom)Goal (directive) failed: pllm:ignore((\+MeTTa_load_context(reloading,true),ignore(load_training),ignore(compile_corpus)))

