;                                           (convert_to_metta_file  done_so_convert_trigram_3 $_162758 tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_trigram_3.pl tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_trigram_3.metta)
  !(encoding iso-latin-1)
  !(dynamic (with_self  (pllm *) (/ trigram 3)))
  !(multifile (with_self  (pllm *) (/ trigram 3)))
  !(module-transparent (with_self  (pllm *) (/ trigram 3)))


  !(dynamic (with_self  (so-convert *) (/ trigram 3)))
  !(multifile (with_self  (so-convert *) (/ trigram 3)))
  !(module-transparent (with_self  (so-convert *) (/ trigram 3)))



