;                                           (convert_to_metta_file  done_so_convert_converting_3 $_268938 tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_converting_3.pl tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_converting_3.metta)

  !(encoding iso-latin-1)
  !(dynamic (with_self  (so-convert *) (/ converting 3)))
  !(multifile (with_self  (so-convert *) (/ converting 3)))
  !(module-transparent (with_self  (so-convert *) (/ converting 3)))



