;                                           (convert_to_metta_file  done_so_convert_tok_split_4 $_62632 tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_tok_split_4.pl tests/performance/gpt2-like/corpus/tmpdata/done_so_convert_tok_split_4.metta)
  !(encoding iso-latin-1)
  !(dynamic (with_self  (pllm *) (/ tok-split 4)))
  !(multifile (with_self  (pllm *) (/ tok-split 4)))
  !(module-transparent (with_self  (pllm *) (/ tok-split 4)))


  !(dynamic (with_self  (so-convert *) (/ tok-split 4)))
  !(multifile (with_self  (so-convert *) (/ tok-split 4)))
  !(module-transparent (with_self  (so-convert *) (/ tok-split 4)))



