#!/bin/bash

SCRIPT=$(readlink -f $0)
export METTA_DIR=$(dirname $SCRIPT)
echo METTA_DIR=$METTA_DIR
cd $METTA_DIR

export FILE=${1}

[ -z "$TEE_FILE" ] && export TEE_FILE="${METTA_DIR}/tee.ansi"
touch $TEE_FILE
chmod 777 $TEE_FILE
[ -z "$TYPESCRIPT" ] && TYPESCRIPT=1 exec /usr/bin/script -f -e -a ${TEE_FILE} -c "TYPESCRIPT=1 $0 $@"

cat /dev/null > ${TEE_FILE}

export BCMD="export TEE_FILE='${TEE_FILE}' ; cd ${METTA_DIR} ; exec swipl -l metta_vspace/pyswip/metta_interp.pl -- --args $@"

echo BCMD="${BCMD}"

bash -c "${BCMD}"

# Check if FILE variable is provided
if [ -f "$FILE" ]; then
	# Extract directory and base name from FILE
	DIRNAME=$(dirname "$FILE")
	BASENAME=$(basename "$FILE" .metta)

	# Execute the command
	cat $FILE $TEE_FILE | ansi2html > "$DIRNAME/$BASENAME.html"

	echo "Output saved to $DIRNAME/$BASENAME.html"
fi



stty sane



