
; 20241014 r.v.v converted metta-lang.dev to metta 
;  !(assertEqualToResult ( )  (  )  ) 
!(import! &amp;self motto)
(= (doc get_current_weather)
   (Doc
     (description )
     (parameters
       (location  ())
     )
   )
)
(= (get_current_weather ($arg) $msgs)
   (if (contains-str $arg)
       (if (contains-str $arg)
           (concat-str (concat-str  $arg)
)
    )
  )
)
!((echo-agent)
   (user ) 
   (Function get_current_weather) ; The temperature in London is 70 Fahrenheit.
)

;  !(assertEqualToResult ( )  (  )  ) 
