
; 20241007 R.v.Vessum converted python source to metta 
; FILE: 83../../../hyperon-experimental/python/tests/test_atom.py :134
; <pre>
        self.assertEqual(AtomKind.GROUNDED.name, str(result[0]['atom_type']))
;</pre>
  !(assertEqualToResult ( )  (  )  )
; <br> lastline 134 <br> 
 

; <pre>
        self.assertEqual(S("MatchableAtom").get_name(), str(result[0]['Z']))
;</pre>

; <br>  lastline 16 <br> 
