
; 20241007 R.v.Vessum converted python source to metta 
; FILE: 82../../../hyperon-experimental/python/tests/test_atom.py :129
; <pre>
        self.assertEqual(AtomKind.SYMBOL.name, str(result[0]['atom_type']))
;</pre>
  !(assertEqualToResult ( )  (  )  )
; <br> lastline 129 <br> 
 

; <pre>
        self.assertEqual(AtomKind.EXPR.name, str(result[0]['atom_type']))
;</pre>

; <br>  lastline 134 <br> 
