
; 20241007 R.v.Vessum converted python source to metta 
; FILE: 97../../../hyperon-experimental/python/tests/test_bindings.py :42
; <pre>
                self.assertEqual(self.bindings, cloned)
;</pre>
  !(assertEqualToResult ( )  (  )  )
; <br> lastline 42 <br> 
 

; <pre>
                self.assertEqual(cloned, cloned_explicitly)
;</pre>

; <br> lastline 43 <br> 
 

; <pre>
        self.assertEqual(self.bindings, self.bindings)
;</pre>

; <br> lastline 45 <br> 
 

; <pre>
        self.assertEqual(self.emptyBindings, self.emptyBindings)
;</pre>

; <br>  lastline 51 <br> 
