
; 20241007 R.v.Vessum converted python source to metta 
; FILE: 79../../../hyperon-experimental/python/tests/test_atom.py :102
; <pre>
        self.assertEqual(interpret(space, E(Atoms.METTA, expr, AtomType.UNDEFINED, G(space))),
                [E(S('Error'), expr, S('Grounded operation which is defined using unwrap=False should return atom instead of Python type'))])
;</pre>
  !(assertEqualToResult ( )  (  )  )
; <br>  lastline 115 <br> 
