
; 20241007 R.v.Vessum converted python source to metta 
; FILE: 25../../../hyperon-experimental/python/tests/test_stdlib.py :21
; <pre>
; 9. 20241007 R.v.Vessum converted python source to metta 
;!(assertEqualToResult (parse "(A 2 \      [[E(S("A" &nbsp &nbsp ) 
;</pre>
  !(assertEqualToResult ( )  (  )  )
; <br> lastline 22 <br> 
 

; <pre>
; 10. 20241007 R.v.Vessum converted python source to metta 
;!(assertEqualToResult (stringToChars "ABC")        [[E(ValueAtom(Char("A" &nbsp &nbsp ) 
;</pre>

; <br> lastline 25 <br> 
 

; <pre>
;        self.assertEqualMettaRunnerResults(metta.run("!(charsToString ('A' 'B' 'C'))"),
;                                           [[ValueAtom("ABC")]])
;</pre>

; <br>  lastline 32 <br> 
