
  (= 
    (trigram  do you think 4489) True)
  (= 
    (trigram  do you like 3754) True)
  (= 
    (trigram  a lot of 3356) True)
  (= 
    (trigram  do you like 3001) True)
  (= 
    (trigram  what do you 2825) True)
  (= 
    (trigram  is your favorite 2400) True)
  (= 
    (trigram  i dont know 2166) True)
  (= 
    (trigram  do you think 2114) True)
  (= 
    (trigram  have you seen 2062) True)
  (= 
    (trigram  i dont know 1892) True)
  (= 
    (trigram  one of the 1569) True)
  (= 
    (trigram  did you see 1525) True)
  (= 
    (trigram  i dont think 1480) True)
  (= 
    (trigram  what is your 1425) True)
  (= 
    (trigram  did you see 1365) True)
  (= 
    (trigram  one of the 1325) True)
  (= 
    (trigram  i think it 1277) True)
  (= 
    (trigram  i like the 1214) True)
  (= 
    (trigram  i dont think 1186) True)
  (= 
    (trigram  i think the 1183) True)
  (= 
    (trigram  you think of 1172) True)
  (= 
    (trigram  i think the 1144) True)
  (= 
    (trigram  it was a 1135) True)
  (= 
    (trigram  whats your favorite 1099) True)
  (= 
    (trigram  i really like 1079) True)
  (= 
    (trigram  do you mean 1068) True)
  (= 
    (trigram  i think i 1059) True)
  (= 
    (trigram  i think they 1037) True)
  (= 
    (trigram  one of my 1030) True)
  (= 
    (trigram  did you like 1030) True)
  (= 
    (trigram  i think they 978) True)
  (= 
    (trigram  i think i 958) True)
  (= 
    (trigram  that is a 952) True)
  (= 
    (trigram  what did you 951) True)
  (= 
    (trigram  you like the 927) True)
  (= 
    (trigram  have you ever 917) True)
  (= 
    (trigram  do you know 909) True)
  (= 
    (trigram  have you heard 886) True)
  (= 
    (trigram  that was a 873) True)
  (= 
    (trigram  some of the 869) True)
  (= 
    (trigram  who is your 843) True)
  (= 
    (trigram  do you have 843) True)
  (= 
    (trigram  why do you 840) True)
  (= 
    (trigram  did you think 830) True)
  (= 
    (trigram  who do you 808) True)
  (= 
    (trigram  is one of 806) True)
  (= 
    (trigram  i love the 806) True)
  (= 
    (trigram  you seen the 805) True)
  (= 
    (trigram  i love that 800) True)
  (= 
    (trigram  of all time 794) True)
  (= 
    (trigram  i think that 791) True)
  (= 
    (trigram  im not sure 778) True)
  (= 
    (trigram  i think he 775) True)
  (= 
    (trigram  did you know 775) True)
  (= 
    (trigram  that would be 774) True)
  (= 
    (trigram  some of the 774) True)
  (= 
    (trigram  but i think 767) True)
  (= 
    (trigram  going to be 757) True)
  (= 
    (trigram  in the movie 735) True)
  (= 
    (trigram  why do you 732) True)
  (= 
    (trigram  you think about 729) True)
  (= 
    (trigram  of all time 726) True)
  (= 
    (trigram  i think he 721) True)
  (= 
    (trigram  i think so 704) True)
  (= 
    (trigram  is a great 697) True)
  (= 
    (trigram  i want to 695) True)
  (= 
    (trigram  but i think 690) True)
  (= 
    (trigram  it is a 688) True)
  (= 
    (trigram  i love that 686) True)
  (= 
    (trigram  what kind of 676) True)
  (= 
    (trigram  to listen to 676) True)
  (= 
    (trigram  i think so 671) True)
  (= 
    (trigram  i would have 661) True)
  (= 
    (trigram  did you know 655) True)
  (= 
    (trigram  would have to 654) True)
  (= 
    (trigram  thought it was 646) True)
  (= 
    (trigram  of the best 642) True)
  (= 
    (trigram  you see the 637) True)
  (= 
    (trigram  you want to 636) True)
  (= 
    (trigram  i think its 634) True)
  (= 
    (trigram  is the best 631) True)
  (= 
    (trigram  i thought it 629) True)
  (= 
    (trigram  i would have 622) True)
  (= 
    (trigram  it would be 621) True)
  (= 
    (trigram  have to say 613) True)
  (= 
    (trigram  yes it was 611) True)
  (= 
    (trigram  when i was 610) True)
  (= 
    (trigram  think it was 604) True)
  (= 
    (trigram  the first one 596) True)
  (= 
    (trigram  whats your favorite 582) True)
  (= 
    (trigram  was your favorite 574) True)
  (= 
    (trigram  a fan of 574) True)
  (= 
    (trigram  you have a 566) True)
  (= 
    (trigram  to be a 565) True)
  (= 
    (trigram  yes it is 564) True)
  (= 
    (trigram  of my favorite 564) True)
  (= 
    (trigram  is going to 556) True)
  (= 
    (trigram  you listen to 554) True)
  (= 
    (trigram  is a good 554) True)
  (= 
    (trigram  did you ever 552) True)
  (= 
    (trigram  you think the 551) True)
  (= 
    (trigram  i would say 551) True)
  (= 
    (trigram  i really liked 545) True)
  (= 
    (trigram  how do you 543) True)
  (= 
    (trigram  im not sure 542) True)
  (= 
    (trigram  check it out 542) True)
  (= 
    (trigram  they have a 540) True)
  (= 
    (trigram  what you mean 533) True)
  (= 
    (trigram  i am not 532) True)
  (= 
    (trigram  yeah i think 527) True)
  (= 
    (trigram  to see it 527) True)
  (= 
    (trigram  i like that 524) True)
  (= 
    (trigram  yeah it was 513) True)
  (= 
    (trigram  he is a 511) True)
  (= 
    (trigram  do you remember 511) True)
  (= 
    (trigram  ill have to 508) True)
  (= 
    (trigram  was a great 506) True)
  (= 
    (trigram  he was a 500) True)
  (= 
    (trigram  yes it is 494) True)
  (= 
    (trigram  i know i 492) True)
  (= 
    (trigram  your favorite song 488) True)
  (= 
    (trigram  at the end 488) True)
  (= 
    (trigram  was a good 485) True)
  (= 
    (trigram  a good one 483) True)
  (= 
    (trigram  thats a good 476) True)
  (= 
    (trigram  i liked the 473) True)
  (= 
    (trigram  what was the 472) True)
  (= 
    (trigram  i can see 461) True)
  (= 
    (trigram  i didnt know 456) True)
  (= 
    (trigram  i cant wait 456) True)
  (= 
    (trigram  in that movie 454) True)
  (= 
    (trigram  i do not 454) True)
  (= 
    (trigram  back in the 454) True)
  (= 
    (trigram  when i was 451) True)
  (= 
    (trigram  i have to 451) True)
  (= 
    (trigram  kind of music 443) True)
  (= 
    (trigram  is my favorite 442) True)
  (= 
    (trigram  yes it was 441) True)
  (= 
    (trigram  of the movie 440) True)
  (= 
    (trigram  but i dont 440) True)
  (= 
    (trigram  want to see 439) True)
  (= 
    (trigram  it will be 438) True)
  (= 
    (trigram  i wonder if 437) True)
  (= 
    (trigram  i know what 437) True)
  (= 
    (trigram  i didnt know 433) True)
  (= 
    (trigram  yeah that was 432) True)
  (= 
    (trigram  to see the 432) True)
  (= 
    (trigram  know what you 431) True)
  (= 
    (trigram  the super bowl 429) True)
  (= 
    (trigram  the one with 429) True)
  (= 
    (trigram  what about the 427) True)
  (= 
    (trigram  what is the 424) True)
  (= 
    (trigram  think of the 424) True)
  (= 
    (trigram  you ever seen 423) True)
  (= 
    (trigram  but it was 421) True)
  (= 
    (trigram  think of the 420) True)
  (= 
    (trigram  i used to 420) True)
  (= 
    (trigram  what do 'you,think,of' 415) True)
  (= 
    (trigram  'what,do,you' think of 415) True)
  (= 
    (trigram  have a favorite 413) True)
  (= 
    (trigram  of my favorites 412) True)
  (= 
    (trigram  in the nfl 408) True)
  (= 
    (trigram  a long time 407) True)
  (= 
    (trigram  is that the 405) True)
  (= 
    (trigram  no i havent 403) True)
  (= 
    (trigram  no i havent 402) True)
  (= 
    (trigram  i know i 402) True)
  (= 
    (trigram  will have to 399) True)
  (= 
    (trigram  i know what 399) True)
  (= 
    (trigram  i guess i 398) True)
  (= 
    (trigram  but i dont 398) True)
  (= 
    (trigram  as good as 398) True)
  (= 
    (trigram  you know what 394) True)
  (= 
    (trigram  never heard of 394) True)
  (= 
    (trigram  why is that 393) True)
  (= 
    (trigram  you have to 392) True)
  (= 
    (trigram  beauty and the 389) True)
  (= 
    (trigram  and the beast 388) True)
  (= 
    (trigram  do you listen 385) True)
  (= 
    (trigram  all of the 384) True)
  (= 
    (trigram  i know right 382) True)
  (= 
    (trigram  i have heard 380) True)
  (= 
    (trigram  i know right 379) True)
  (= 
    (trigram  to watch it 377) True)
  (= 
    (trigram  what was your 376) True)
  (= 
    (trigram  do you want 376) True)
  (= 
    (trigram  are you a 374) True)
  (= 
    (trigram  there is a 370) True)
  (= 
    (trigram  it seems like 370) True)
  (= 
    (trigram  i havent seen 369) True)
  (= 
    (trigram  i dont like 369) True)
  (= 
    (trigram  you know that 368) True)
  (= 
    (trigram  i feel like 368) True)
  (= 
    (trigram  have to check 368) True)
  (= 
    (trigram  you think is 367) True)
  (= 
    (trigram  all the time 367) True)
  (= 
    (trigram  what is it 366) True)
  (= 
    (trigram  i did not 362) True)
  (= 
    (trigram  i remember that 360) True)
  (= 
    (trigram  why is that 359) True)
  (= 
    (trigram  im going to 359) True)
  (= 
    (trigram  thats the one 355) True)
  (= 
    (trigram  i also like 352) True)
  (= 
    (trigram  are you a 352) True)
  (= 
    (trigram  are going to 352) True)
  (= 
    (trigram  was the best 351) True)
  (= 
    (trigram  was one of 348) True)
  (= 
    (trigram  you say that 347) True)
  (= 
    (trigram  sounds like a 346) True)
  (= 
    (trigram  did you hear 346) True)
  (= 
    (trigram  i guess i 343) True)
  (= 
    (trigram  back in the 343) True)
  (= 
    (trigram  i loved the 342) True)
  (= 
    (trigram  i heard that 342) True)
  (= 
    (trigram  you think they 341) True)
  (= 
    (trigram  dont think so 341) True)
  (= 
    (trigram  you like it 340) True)
  (= 
    (trigram  on the radio 339) True)
  (= 
    (trigram  i have not 339) True)
  (= 
    (trigram  it was really 338) True)
  (= 
    (trigram  to go to 337) True)
  (= 
    (trigram  i have a 336) True)
  (= 
    (trigram  most of the 335) True)
  (= 
    (trigram  have you been 335) True)
  (= 
    (trigram  i dont like 334) True)
  (= 
    (trigram  a really good 333) True)
  (= 
    (trigram  part of the 331) True)
  (= 
    (trigram  i think you 328) True)
  (= 
    (trigram  to be honest 327) True)
  (= 
    (trigram  any of the 327) True)
  (= 
    (trigram  yeah it was 326) True)
  (= 
    (trigram  i was a 326) True)
  (= 
    (trigram  that is true 325) True)
  (= 
    (trigram  i cant believe 324) True)
  (= 
    (trigram  it was pretty 323) True)
  (= 
    (trigram  have to be 321) True)
  (= 
    (trigram  but it was 321) True)
  (= 
    (trigram  yes i love 317) True)
  (= 
    (trigram  the name of 317) True)
  (= 
    (trigram  i thought the 317) True)
  (= 
    (trigram  i havent heard 317) True)
  (= 
    (trigram  think it is 316) True)
  (= 
    (trigram  a great movie 316) True)
  (= 
    (trigram  i cant believe 315) True)
  (= 
    (trigram  been listening to 315) True)
  (= 
    (trigram  it was the 313) True)
  (= 
    (trigram  a bunch of 312) True)
  (= 
    (trigram  a big fan 312) True)
  (= 
    (trigram  the star wars 311) True)
  (= 
    (trigram  i am a 310) True)
  (= 
    (trigram  you heard of 309) True)
  (= 
    (trigram  i have seen 309) True)
  (= 
    (trigram  i agree with 307) True)
  (= 
    (trigram  music do you 305) True)
  (= 
    (trigram  i listen to 305) True)
  (= 
    (trigram  agree with you 305) True)
  (= 
    (trigram  there is a 304) True)
  (= 
    (trigram  you think that 303) True)
  (= 
    (trigram  you ever see 302) True)
  (= 
    (trigram  'i,know,what' you mean 302) True)
  (= 
    (trigram  dont know if 301) True)
  (= 
    (trigram  star wars movie 300) True)
  (= 
    (trigram  oh yeah i 300) True)
  (= 
    (trigram  was such a 299) True)
  (= 
    (trigram  want to go 299) True)
  (= 
    (trigram  i just saw 298) True)
  (= 
    (trigram  i agree with 298) True)
  (= 
    (trigram  you seen any 297) True)
  (= 
    (trigram  yes i think 297) True)
  (= 
    (trigram  the one with 297) True)
  (= 
    (trigram  yes i do 296) True)
  (= 
    (trigram  listen to it 296) True)
  (= 
    (trigram  it was so 296) True)
  (= 
    (trigram  music do you 295) True)
  (= 
    (trigram  dont think so 295) True)
  (= 
    (trigram  it came out 294) True)
  (= 
    (trigram  i saw the 294) True)
  (= 
    (trigram  i love it 294) True)
  (= 
    (trigram  i do like 294) True)
  (= 
    (trigram  are some of 294) True)
  (= 
    (trigram  yeah i know 293) True)
  (= 
    (trigram  what are you 291) True)
  (= 
    (trigram  i know that 291) True)
  (= 
    (trigram  am not sure 291) True)
  (= 
    (trigram  i saw it 290) True)
  (= 
    (trigram  a great song 289) True)
  (= 
    (trigram  looking forward to 288) True)
  (= 
    (trigram  yes i have 287) True)
  (= 
    (trigram  it was the 287) True)
  (= 
    (trigram  i think she 287) True)
  (= 
    (trigram  thats the one 286) True)
  (= 
    (trigram  'what,do,you' think about 285) True)
  (= 
    (trigram  a good movie 285) True)
  (= 
    (trigram  yes i do 284) True)
  (= 
    (trigram  to be the 284) True)
  (= 
    (trigram  my favorite is 283) True)
  (= 
    (trigram  was pretty good 282) True)
  (= 
    (trigram  think about the 282) True)
  (= 
    (trigram  i will have 282) True)
  (= 
    (trigram  i dont really 282) True)
  (= 
    (trigram  i saw the 281) True)
  (= 
    (trigram  yeah i think 280) True)
  (= 
    (trigram  it came out 280) True)
  (= 
    (trigram  'do,you,have' a favorite 280) True)
  (= 
    (trigram  was really good 279) True)
  (= 
    (trigram  the end of 279) True)
  (= 
    (trigram  it seems like 276) True)
  (= 
    (trigram  i like it 276) True)
  (= 
    (trigram  i saw that 275) True)
  (= 
    (trigram  he has a 275) True)
  (= 
    (trigram  of music do 274) True)
  (= 
    (trigram  it was great 274) True)
  (= 
    (trigram  used to be 273) True)
  (= 
    (trigram  i wish i 273) True)
  (= 
    (trigram  its hard to 272) True)
  (= 
    (trigram  be able to 272) True)
  (= 
    (trigram  in my opinion 269) True)
  (= 
    (trigram  and i think 269) True)
  (= 
    (trigram  who is the 268) True)
  (= 
    (trigram  are you going 268) True)
  (= 
    (trigram  was one of 267) True)
  (= 
    (trigram  they are a 267) True)
  (= 
    (trigram  that sounds like 267) True)
  (= 
    (trigram  i know but 267) True)
  (= 
    (trigram  go to the 267) True)
  (= 
    (trigram  yeah that was 266) True)
  (= 
    (trigram  i hope they 266) True)
  (= 
    (trigram  i do too 266) True)
  (= 
    (trigram  you are right 265) True)
  (= 
    (trigram  yes they are 265) True)
  (= 
    (trigram  star wars movies 265) True)
  (= 
    (trigram  i am a 265) True)
  (= 
    (trigram  have to go 264) True)
  (= 
    (trigram  has to be 264) True)
  (= 
    (trigram  yeah he was 263) True)
  (= 
    (trigram  what are some 262) True)
  (= 
    (trigram  think they will 262) True)
  (= 
    (trigram  really like the 262) True)
  (= 
    (trigram  did you watch 262) True)
  (= 
    (trigram  a great job 262) True)
  (= 
    (trigram  you going to 261) True)
  (= 
    (trigram  most of the 261) True)
  (= 
    (trigram  i cant wait 260) True)
  (= 
    (trigram  think they are 258) True)
  (= 
    (trigram  is in it 258) True)
  (= 
    (trigram  i dont really 258) True)
  (= 
    (trigram  have a lot 258) True)
  (= 
    (trigram  didnt know that 258) True)
  (= 
    (trigram  i hope so 256) True)
  (= 
    (trigram  i do too 256) True)
  (= 
    (trigram  have a good 256) True)
  (= 
    (trigram  lot of people 255) True)
  (= 
    (trigram  i know that 255) True)
  (= 
    (trigram  a little bit 255) True)
  (= 
    (trigram  a few years 255) True)
  (= 
    (trigram  big fan of 254) True)
  (= 
    (trigram  yes he is 253) True)
  (= 
    (trigram  all of them 253) True)
  (= 
    (trigram  what about you 252) True)
  (= 
    (trigram  he was the 252) True)
  (= 
    (trigram  would have been 250) True)
  (= 
    (trigram  seen the movie 250) True)
  (= 
    (trigram  i think thats 250) True)
  (= 
    (trigram  would be a 249) True)
  (= 
    (trigram  heard of them 249) True)
  (= 
    (trigram  yes that is 248) True)
  (= 
    (trigram  that one too 248) True)
  (= 
    (trigram  like that one 248) True)
  (= 
    (trigram  fan of the 248) True)
  (= 
    (trigram  i would love 247) True)
  (= 
    (trigram  i havent seen 247) True)
  (= 
    (trigram  and it was 247) True)
  (= 
    (trigram  that song is 246) True)
  (= 
    (trigram  cant wait to 246) True)
  (= 
    (trigram  but it is 246) True)
  (= 
    (trigram  came out in 245) True)
  (= 
    (trigram  agree with that 245) True)
  (= 
    (trigram  there was a 244) True)
  (= 
    (trigram  to have a 243) True)
  (= 
    (trigram  thats a great 243) True)
  (= 
    (trigram  was the best 242) True)
  (= 
    (trigram  a couple of 242) True)
  (= 
    (trigram  you mean the 241) True)
  (= 
    (trigram  out of the 241) True)
  (= 
    (trigram  i have been 241) True)
  (= 
    (trigram  all of them 241) True)
  (= 
    (trigram  i like them 240) True)
  (= 
    (trigram  you like to 239) True)
  (= 
    (trigram  the first time 238) True)
  (= 
    (trigram  i liked it 238) True)
  (= 
    (trigram  you know the 237) True)
  (= 
    (trigram  that is the 237) True)
  (= 
    (trigram  i thought the 237) True)
  (= 
    (trigram  i loved it 237) True)
  (= 
    (trigram  was in the 236) True)
  (= 
    (trigram  it sounds like 236) True)
  (= 
    (trigram  is such a 236) True)
  (= 
    (trigram  but i do 236) True)
  (= 
    (trigram  you think will 235) True)
  (= 
    (trigram  he was in 235) True)
  (= 
    (trigram  do you say 235) True)
  (= 
    (trigram  as long as 235) True)
  (= 
    (trigram  seen the new 234) True)
  (= 
    (trigram  me too i 234) True)
  (= 
    (trigram  yeah i like 233) True)
  (= 
    (trigram  more of a 233) True)
  (= 
    (trigram  yes they are 232) True)
  (= 
    (trigram  to go with 232) True)
  (= 
    (trigram  that the one 232) True)
  (= 
    (trigram  didnt know that 232) True)
  (= 
    (trigram  think is the 231) True)
  (= 
    (trigram  was such a 230) True)
  (= 
    (trigram  want to watch 230) True)
  (= 
    (trigram  to go see 229) True)
  (= 
    (trigram  like to see 229) True)
  (= 
    (trigram  'i,would,have' to say 229) True)
  (= 
    (trigram  in the first 229) True)
  (= 
    (trigram  i know it 229) True)
  (= 
    (trigram  yeah i know 228) True)
  (= 
    (trigram  would love to 228) True)
  (= 
    (trigram  the other day 228) True)
  (= 
    (trigram  i love them 228) True)
  (= 
    (trigram  your favorite disney 227) True)
  (= 
    (trigram  that one is 227) True)
  (= 
    (trigram  see the new 227) True)
  (= 
    (trigram  in the end 227) True)
  (= 
    (trigram  favorite disney movie 227) True)
  (= 
    (trigram  you like about 226) True)
  (= 
    (trigram  yeah me too 226) True)
  (= 
    (trigram  yes i did 225) True)
  (= 
    (trigram  oh i love 225) True)
  (= 
    (trigram  i would like 225) True)
  (= 
    (trigram  better than the 225) True)
  (= 
    (trigram  a good job 225) True)
  (= 
    (trigram  to see them 224) True)
  (= 
    (trigram  to do with 224) True)
  (= 
    (trigram  there are a 224) True)
  (= 
    (trigram  listen to the 224) True)
  (= 
    (trigram  yeah me too 223) True)
  (= 
    (trigram  thats what i 222) True)
  (= 
    (trigram  yes i have 221) True)
  (= 
    (trigram  but i like 221) True)
  (= 
    (trigram  you ever heard 220) True)
  (= 
    (trigram  to watch the 220) True)
  (= 
    (trigram  that was the 220) True)
  (= 
    (trigram  of course i 220) True)
  (= 
    (trigram  and i think 220) True)
  (= 
    (trigram  in that one 219) True)
  (= 
    (trigram  they had a 217) True)
  (= 
    (trigram  i was thinking 217) True)
  (= 
    (trigram  yeah i guess 216) True)
  (= 
    (trigram  that makes sense 216) True)
  (= 
    (trigram  to check it 215) True)
  (= 
    (trigram  supposed to be 215) True)
  (= 
    (trigram  of the galaxy 215) True)
  (= 
    (trigram  yes i did 214) True)
  (= 
    (trigram  he had a 214) True)
  (= 
    (trigram  was kind of 213) True)
  (= 
    (trigram  not at all 213) True)
  (= 
    (trigram  you mean the 212) True)
  (= 
    (trigram  you know who 212) True)
  (= 
    (trigram  yeah it is 212) True)
  (= 
    (trigram  in the league 212) True)
  (= 
    (trigram  you have any 211) True)
  (= 
    (trigram  i went to 210) True)
  (= 
    (trigram  i hope they 210) True)
  (= 
    (trigram  love that song 209) True)
  (= 
    (trigram  it was good 209) True)
  (= 
    (trigram  i am sure 209) True)
  (= 
    (trigram  can see that 209) True)
  (= 
    (trigram  but i really 209) True)
  (= 
    (trigram  i need to 208) True)
  (= 
    (trigram  you a fan 207) True)
  (= 
    (trigram  type of music 207) True)
  (= 
    (trigram  sounds like a 207) True)
  (= 
    (trigram  but it is 207) True)
  (= 
    (trigram  the force awakens 206) True)
  (= 
    (trigram  of course i 206) True)
  (= 
    (trigram  id have to 206) True)
  (= 
    (trigram  yes that was 205) True)
  (= 
    (trigram  yes he is 205) True)
  (= 
    (trigram  'why,do,you' say that 205) True)
  (= 
    (trigram  was a little 205) True)
  (= 
    (trigram  no i dont 205) True)
  (= 
    (trigram  its hard to 205) True)
  (= 
    (trigram  i know but 205) True)
  (= 
    (trigram  give it a 205) True)
  (= 
    (trigram  i havent heard 204) True)
  (= 
    (trigram  have to watch 204) True)
  (= 
    (trigram  are there any 203) True)
  (= 
    (trigram  you talking about 202) True)
  (= 
    (trigram  well i think 202) True)
  (= 
    (trigram  think he is 202) True)
  (= 
    (trigram  no i dont 202) True)
  (= 
    (trigram  guardians of the 202) True)
  (= 
    (trigram  dont think i 202) True)
  (= 
    (trigram  a bit of 202) True)
  (= 
    (trigram  there are so 201) True)
  (= 
    (trigram  that one was 201) True)
  (= 
    (trigram  of their songs 201) True)
  (= 
    (trigram  i wish i 201) True)
  (= 
    (trigram  is it about 201) True)
  (= 
    (trigram  like a lot 200) True)
  (= 
    (trigram  i like to 200) True)
  (= 
    (trigram  who was the 199) True)
  (= 
    (trigram  i know it 199) True)
  (= 
    (trigram  i heard it 199) True)
  (= 
    (trigram  are so many 199) True)
  (= 
    (trigram  you watch the 198) True)
  (= 
    (trigram  one of those 198) True)
  (= 
    (trigram  one of his 198) True)
  (= 
    (trigram  no but i 198) True)
  (= 
    (trigram  fast and furious 198) True)
  (= 
    (trigram  whos your favorite 197) True)
  (= 
    (trigram  think i have 197) True)
  (= 
    (trigram  the rest of 197) True)
  (= 
    (trigram  that one was 197) True)
  (= 
    (trigram  its one of 197) True)
  (= 
    (trigram  he is the 197) True)
  (= 
    (trigram  do you feel 197) True)
  (= 
    (trigram  but i do 197) True)
  (= 
    (trigram  a pretty good 197) True)
  (= 
    (trigram  your favorite character 196) True)
  (= 
    (trigram  that song is 196) True)
  (= 
    (trigram  such a great 196) True)
  (= 
    (trigram  some of his 196) True)
  (= 
    (trigram  as well as 196) True)
  (= 
    (trigram  going to see 195) True)
  (= 
    (trigram  fun to watch 195) True)
  (= 
    (trigram  your favorite movie 194) True)
  (= 
    (trigram  i like her 194) True)
  (= 
    (trigram  heard of it 194) True)
  (= 
    (trigram  let me know 193) True)
  (= 
    (trigram  i loved that 193) True)
  (= 
    (trigram  i kind of 193) True)
  (= 
    (trigram  you know i 192) True)
  (= 
    (trigram  ever heard of 192) True)
  (= 
    (trigram  you remember the 191) True)
  (= 
    (trigram  wait to see 191) True)
  (= 
    (trigram  it was just 191) True)
  (= 
    (trigram  go see it 191) True)
  (= 
    (trigram  going to have 191) True)
  (= 
    (trigram  some of their 189) True)
  (= 
    (trigram  lets talk about 189) True)
  (= 
    (trigram  ive heard of 189) True)
  (= 
    (trigram  i just dont 189) True)
  (= 
    (trigram  yeah but i 188) True)
  (= 
    (trigram  will be a 187) True)
  (= 
    (trigram  if you want 187) True)
  (= 
    (trigram  how did you 187) True)
  (= 
    (trigram  the star wars 186) True)
  (= 
    (trigram  that movie was 186) True)
  (= 
    (trigram  kind of like 186) True)
  (= 
    (trigram  it was just 186) True)
  (= 
    (trigram  i like a 186) True)
  (= 
    (trigram  yeah it is 185) True)
  (= 
    (trigram  for a while 185) True)
  (= 
    (trigram  would like to 184) True)
  (= 
    (trigram  what was it 184) True)
  (= 
    (trigram  talking to you 184) True)
  (= 
    (trigram  i have no 184) True)
  (= 
    (trigram  i dont remember 184) True)
  (= 
    (trigram  i agree i 184) True)
  (= 
    (trigram  had a lot 184) True)
  (= 
    (trigram  yes i love 183) True)
  (= 
    (trigram  wow that is 183) True)
  (= 
    (trigram  was a kid 183) True)
  (= 
    (trigram  to see that 183) True)
  (= 
    (trigram  the movie was 183) True)
  (= 
    (trigram  thats what i 183) True)
  (= 
    (trigram  what are your 182) True)
  (= 
    (trigram  name of the 182) True)
  (= 
    (trigram  it really is 182) True)
  (= 
    (trigram  was going to 181) True)
  (= 
    (trigram  the lion king 181) True)
  (= 
    (trigram  he is the 181) True)
  (= 
    (trigram  heard of that 181) True)
  (= 
    (trigram  but i have 181) True)
  (= 
    (trigram  back to the 181) True)
  (= 
    (trigram  what is that 180) True)
  (= 
    (trigram  to be in 180) True)
  (= 
    (trigram  my favorite song 180) True)
  (= 
    (trigram  thats a good 179) True)
  (= 
    (trigram  it sounds like 179) True)
  (= 
    (trigram  i liked that 179) True)
  (= 
    (trigram  i didnt like 179) True)
  (= 
    (trigram  who is in 178) True)
  (= 
    (trigram  tell me about 178) True)
  (= 
    (trigram  like the song 178) True)
  (= 
    (trigram  kind of a 178) True)
  (= 
    (trigram  i think hes 178) True)
  (= 
    (trigram  all time favorite 178) True)
  (= 
    (trigram  a good song 178) True)
  (= 
    (trigram  love that movie 177) True)
  (= 
    (trigram  i have never 177) True)
  (= 
    (trigram  end of the 177) True)
  (= 
    (trigram  yeah i love 176) True)
  (= 
    (trigram  what 'did,you,think' of 176) True)
  (= 
    (trigram  'what,did,you' think of 176) True)
  (= 
    (trigram  havent seen it 176) True)
  (= 
    (trigram  going to the 176) True)
  (= 
    (trigram  but i really 176) True)
  (= 
    (trigram  you feel about 175) True)
  (= 
    (trigram  yeah he is 175) True)
  (= 
    (trigram  think about it 175) True)
  (= 
    (trigram  the movie is 175) True)
  (= 
    (trigram  that it was 175) True)
  (= 
    (trigram  she is a 175) True)
  (= 
    (trigram  pirates of the 175) True)
  (= 
    (trigram  i agree but 175) True)
  (= 
    (trigram  yes he was 174) True)
  (= 
    (trigram  ive never heard 174) True)
  (= 
    (trigram  has a lot 174) True)
  (= 
    (trigram  dont want to 174) True)
  (= 
    (trigram  a lot more 174) True)
  (= 
    (trigram  ever seen the 173) True)
  (= 
    (trigram  when he was 172) True)
  (= 
    (trigram  to watch the 172) True)
  (= 
    (trigram  such a good 172) True)
  (= 
    (trigram  it is so 172) True)
  (= 
    (trigram  as much as 172) True)
  (= 
    (trigram  oh i love 171) True)
  (= 
    (trigram  no i think 171) True)
  (= 
    (trigram  it to the 171) True)
  (= 
    (trigram  i love her 171) True)
  (= 
    (trigram  i dont remember 171) True)
  (= 
    (trigram  be a good 171) True)
  (= 
    (trigram  of the most 170) True)
  (= 
    (trigram  no i didnt 170) True)
  (= 
    (trigram  i guess so 170) True)
  (= 
    (trigram  favorite star wars 170) True)
  (= 
    (trigram  did a great 170) True)
  (= 
    (trigram  one of their 169) True)
  (= 
    (trigram  i just dont 169) True)
  (= 
    (trigram  good as the 169) True)
  (= 
    (trigram  you see that 168) True)
  (= 
    (trigram  how are you 168) True)
  (= 
    (trigram  yeah he was 167) True)
  (= 
    (trigram  when it comes 167) True)
  (= 
    (trigram  movies do you 167) True)
  (= 
    (trigram  is really good 167) True)
  (= 
    (trigram  im not a 167) True)
  (= 
    (trigram  really liked the 166) True)
  (= 
    (trigram  i wonder what 166) True)
  (= 
    (trigram  i forgot about 166) True)
  (= 
    (trigram  but they are 166) True)
  (= 
    (trigram  be in the 166) True)
  (= 
    (trigram  as a kid 166) True)
  (= 
    (trigram  would you say 165) True)
  (= 
    (trigram  oh yeah i 165) True)
  (= 
    (trigram  it has a 165) True)
  (= 
    (trigram  in the day 165) True)
  (= 
    (trigram  i guess that 165) True)
  (= 
    (trigram  empire strikes back 165) True)
  (= 
    (trigram  are you talking 165) True)
  (= 
    (trigram  love to see 164) True)
  (= 
    (trigram  i guess it 164) True)
  (= 
    (trigram  but i have 164) True)
  (= 
    (trigram  lot of the 163) True)
  (= 
    (trigram  i just watched 163) True)
  (= 
    (trigram  a huge fan 163) True)
  (= 
    (trigram  it is the 162) True)
  (= 
    (trigram  it is so 162) True)
  (= 
    (trigram  it but i 162) True)
  (= 
    (trigram  i know its 162) True)
  (= 
    (trigram  check them out 162) True)
  (= 
    (trigram  but i am 162) True)
  (= 
    (trigram  you know i 161) True)
  (= 
    (trigram  yes that is 161) True)
  (= 
    (trigram  yeah they are 161) True)
  (= 
    (trigram  of the jedi 161) True)
  (= 
    (trigram  lets talk about 161) True)
  (= 
    (trigram  i like him 161) True)
  (= 
    (trigram  i guess you 161) True)
  (= 
    (trigram  but im not 161) True)
  (= 
    (trigram  yes i like 160) True)
  (= 
    (trigram  was the last 160) True)
  (= 
    (trigram  thats for sure 160) True)
  (= 
    (trigram  oh i see 160) True)
  (= 
    (trigram  like that song 160) True)
  (= 
    (trigram  is it a 160) True)
  (= 
    (trigram  is in the 160) True)
  (= 
    (trigram  have no idea 160) True)
  (= 
    (trigram  you should check 159) True)
  (= 
    (trigram  well i guess 159) True)
  (= 
    (trigram  to a lot 159) True)
  (= 
    (trigram  return of the 159) True)
  (= 
    (trigram  over and over 159) True)
  (= 
    (trigram  favorite song by 159) True)
  (= 
    (trigram  do you ever 159) True)
  (= 
    (trigram  to see how 158) True)
  (= 
    (trigram  to see a 158) True)
  (= 
    (trigram  the second one 158) True)
  (= 
    (trigram  the same thing 158) True)
  (= 
    (trigram  seen any good 158) True)
  (= 
    (trigram  heard of the 158) True)
  (= 
    (trigram  fun to watch 158) True)
  (= 
    (trigram  what type of 157) True)
  (= 
    (trigram  lot of good 157) True)
  (= 
    (trigram  is a classic 157) True)
  (= 
    (trigram  i heard it 157) True)
  (= 
    (trigram  a ton of 157) True)
  (= 
    (trigram  you heard the 156) True)
  (= 
    (trigram  yes but i 156) True)
  (= 
    (trigram  was in it 156) True)
  (= 
    (trigram  the last one 156) True)
  (= 
    (trigram  rest of the 156) True)
  (= 
    (trigram  oh i see 156) True)
  (= 
    (trigram  not sure if 156) True)
  (= 
    (trigram  i wish they 156) True)
  (= 
    (trigram  i know they 156) True)
  (= 
    (trigram  cant wait for 156) True)
  (= 
    (trigram  was the first 155) True)
  (= 
    (trigram  think so too 155) True)
  (= 
    (trigram  the one that 155) True)
  (= 
    (trigram  the little mermaid 155) True)
  (= 
    (trigram  seems to be 155) True)
  (= 
    (trigram  if you like 155) True)
  (= 
    (trigram  hey have you 155) True)
  (= 
    (trigram  he was so 155) True)
  (= 
    (trigram  the same way 154) True)
  (= 
    (trigram  the harry potter 154) True)
  (= 
    (trigram  i didnt like 154) True)
  (= 
    (trigram  which one is 153) True)
  (= 
    (trigram  that kind of 153) True)
  (= 
    (trigram  of all the 153) True)
  (= 
    (trigram  is the most 153) True)
  (= 
    (trigram  i guess so 153) True)
  (= 
    (trigram  i am so 153) True)
  (= 
    (trigram  have a great 153) True)
  (= 
    (trigram  came out in 153) True)
  (= 
    (trigram  you think he 152) True)
  (= 
    (trigram  yeah i like 152) True)
  (= 
    (trigram  what happened to 152) True)
  (= 
    (trigram  thats one of 152) True)
  (= 
    (trigram  of his songs 152) True)
  (= 
    (trigram  i know they 152) True)
  (= 
    (trigram  have to see 152) True)
  (= 
    (trigram  dont know i 152) True)
  (= 
    (trigram  at the time 152) True)
  (= 
    (trigram  the one where 151) True)
  (= 
    (trigram  thats a tough 151) True)
  (= 
    (trigram  i think we 151) True)
  (= 
    (trigram  i know its 151) True)
  (= 
    (trigram  have to agree 151) True)
  (= 
    (trigram  yeah i saw 150) True)
  (= 
    (trigram  was my favorite 150) True)
  (= 
    (trigram  the end of 150) True)
  (= 
    (trigram  of your favorite 150) True)
  (= 
    (trigram  i wonder how 150) True)
  (= 
    (trigram  i thought that 150) True)
  (= 
    (trigram  i still think 150) True)
  (= 
    (trigram  i could see 150) True)
  (= 
    (trigram  i am going 150) True)
  (= 
    (trigram  but i am 150) True)
  (= 
    (trigram  think of it 149) True)
  (= 
    (trigram  there are some 149) True)
  (= 
    (trigram  some of them 149) True)
  (= 
    (trigram  one of them 149) True)
  (= 
    (trigram  it was very 149) True)
  (= 
    (trigram  i really enjoyed 149) True)
  (= 
    (trigram  have heard of 149) True)
  (= 
    (trigram  all the way 149) True)
  (= 
    (trigram  you think it 148) True)
  (= 
    (trigram  your favorite team 148) True)
  (= 
    (trigram  you dont like 148) True)
  (= 
    (trigram  they need to 148) True)
  (= 
    (trigram  they have to 148) True)
  (= 
    (trigram  the same time 148) True)
  (= 
    (trigram  the first movie 148) True)
  (= 
    (trigram  some of your 148) True)
  (= 
    (trigram  no i have 148) True)
  (= 
    (trigram  i know he 148) True)
  (= 
    (trigram  heard of him 148) True)
  (= 
    (trigram  but he was 148) True)
  (= 
    (trigram  yeah i remember 147) True)
  (= 
    (trigram  yeah he is 147) True)
  (= 
    (trigram  whats it about 147) True)
  (= 
    (trigram  was a bit 147) True)
  (= 
    (trigram  think he was 147) True)
  (= 
    (trigram  i think we 147) True)
  (= 
    (trigram  is kind of 147) True)
  (= 
    (trigram  im going to 147) True)
  (= 
    (trigram  how about the 147) True)
  (= 
    (trigram  a new album 147) True)
  (= 
    (trigram  to see him 146) True)
  (= 
    (trigram  to make a 146) True)
  (= 
    (trigram  the fact that 146) True)
  (= 
    (trigram  something like that 146) True)
  (= 
    (trigram  it would have 146) True)
  (= 
    (trigram  in the playoffs 146) True)
  (= 
    (trigram  i like how 146) True)
  (= 
    (trigram  but i still 146) True)
  (= 
    (trigram  whats it about 145) True)
  (= 
    (trigram  not sure i 145) True)
  (= 
    (trigram  like some of 145) True)
  (= 
    (trigram  ever listen to 145) True)
  (= 
    (trigram  yeah that is 144) True)
  (= 
    (trigram  yeah i dont 144) True)
  (= 
    (trigram  the new one 144) True)
  (= 
    (trigram  of the songs 144) True)
  (= 
    (trigram  love that one 144) True)
  (= 
    (trigram  listen to them 144) True)
  (= 
    (trigram  its going to 144) True)
  (= 
    (trigram  hey do you 144) True)
  (= 
    (trigram  do you watch 144) True)
  (= 
    (trigram  a great one 144) True)
  (= 
    (trigram  that it was 143) True)
  (= 
    (trigram  is a really 143) True)
  (= 
    (trigram  i just think 143) True)
  (= 
    (trigram  because of the 143) True)
  (= 
    (trigram  your favorite part 142) True)
  (= 
    (trigram  yeah i dont 142) True)
  (= 
    (trigram  to the movies 142) True)
  (= 
    (trigram  so what do 142) True)
  (= 
    (trigram  she has a 142) True)
  (= 
    (trigram  of the new 142) True)
  (= 
    (trigram  not sure if 142) True)
  (= 
    (trigram  must have been 142) True)
  (= 
    (trigram  i know the 142) True)
  (= 
    (trigram  i dont want 142) True)
  (= 
    (trigram  yes i am 141) True)
  (= 
    (trigram  was a really 141) True)
  (= 
    (trigram  they did a 141) True)
  (= 
    (trigram  that came out 141) True)
  (= 
    (trigram  thank you for 141) True)
  (= 
    (trigram  oh i know 141) True)
  (= 
    (trigram  for the first 141) True)
  (= 
    (trigram  but they are 141) True)
  (= 
    (trigram  you dont like 140) True)
  (= 
    (trigram  wow that is 140) True)
  (= 
    (trigram  think that the 140) True)
  (= 
    (trigram  think that is 140) True)
  (= 
    (trigram  think it will 140) True)
  (= 
    (trigram  pirates of the 140) True)
  (= 
    (trigram  it in the 140) True)
  (= 
    (trigram  is in the 140) True)
  (= 
    (trigram  you ever listen 139) True)
  (= 
    (trigram  will be the 139) True)
  (= 
    (trigram  to say the 139) True)
  (= 
    (trigram  ive heard that 139) True)
  (= 
    (trigram  it is the 139) True)
  (= 
    (trigram  i thought he 139) True)
  (= 
    (trigram  i know the 139) True)
  (= 
    (trigram  dont know about 139) True)
  (= 
    (trigram  did not know 139) True)
  (= 
    (trigram  did a good 139) True)
  (= 
    (trigram  who was your 138) True)
  (= 
    (trigram  thats why i 138) True)
  (= 
    (trigram  it is really 138) True)
  (= 
    (trigram  in love with 138) True)
  (= 
    (trigram  heard that one 138) True)
  (= 
    (trigram  you like any 137) True)
  (= 
    (trigram  the fast and 137) True)
  (= 
    (trigram  its a good 137) True)
  (= 
    (trigram  did you get 137) True)
  (= 
    (trigram  a few of 137) True)
  (= 
    (trigram  yes that was 136) True)
  (= 
    (trigram  yes i agree 136) True)
  (= 
    (trigram  was so good 136) True)
  (= 
    (trigram  think they have 136) True)
  (= 
    (trigram  seen that one 136) True)
  (= 
    (trigram  me too i 136) True)
  (= 
    (trigram  i totally agree 136) True)
  (= 
    (trigram  i think there 136) True)
  (= 
    (trigram  is pretty good 136) True)
  (= 
    (trigram  i really love 136) True)
  (= 
    (trigram  him in the 136) True)
  (= 
    (trigram  he will be 136) True)
  (= 
    (trigram  'have,you,seen' the movie 136) True)
  (= 
    (trigram  dont think they 136) True)
  (= 
    (trigram  your favorite star 135) True)
  (= 
    (trigram  not as good 135) True)
  (= 
    (trigram  i watched it 135) True)
  (= 
    (trigram  its kind of 135) True)
  (= 
    (trigram  i had to 135) True)
  (= 
    (trigram  you need to 134) True)
  (= 
    (trigram  well it was 134) True)
  (= 
    (trigram  that he was 134) True)
  (= 
    (trigram  songs do you 134) True)
  (= 
    (trigram  my all time 134) True)
  (= 
    (trigram  i was just 134) True)
  (= 
    (trigram  it had a 134) True)
  (= 
    (trigram  i know he 134) True)
  (= 
    (trigram  dont know if 134) True)
  (= 
    (trigram  do not think 134) True)
  (= 
    (trigram  to talk about 133) True)
  (= 
    (trigram  thought he was 133) True)
  (= 
    (trigram  on that album 133) True)
  (= 
    (trigram  oh yeah that 133) True)
  (= 
    (trigram  movies do you 133) True)
  (= 
    (trigram  it is not 133) True)
  (= 
    (trigram  it could be 133) True)
  (= 
    (trigram  how was it 133) True)
  (= 
    (trigram  have been a 133) True)
  (= 
    (trigram  has a great 133) True)
  (= 
    (trigram  go to a 133) True)
  (= 
    (trigram  dont know but 133) True)
  (= 
    (trigram  yes he was 132) True)
  (= 
    (trigram  think i will 132) True)
  (= 
    (trigram  think it was 132) True)
  (= 
    (trigram  that movie is 132) True)
  (= 
    (trigram  new star wars 132) True)
  (= 
    (trigram  my all time 132) True)
  (= 
    (trigram  it looks like 132) True)
  (= 
    (trigram  i like some 132) True)
  (= 
    (trigram  but there are 132) True)
  (= 
    (trigram  am going to 132) True)
  (= 
    (trigram  would be great 131) True)
  (= 
    (trigram  'when,i,was' a kid 131) True)
  (= 
    (trigram  to see a 131) True)
  (= 
    (trigram  think that was 131) True)
  (= 
    (trigram  long time ago 131) True)
  (= 
    (trigram  its a great 131) True)
  (= 
    (trigram  it is really 131) True)
  (= 
    (trigram  i am so 131) True)
  (= 
    (trigram  dont you think 131) True)
  (= 
    (trigram  as well as 131) True)
  (= 
    (trigram  reminds me of 130) True)
  (= 
    (trigram  i think my 130) True)
  (= 
    (trigram  forgot about that 130) True)
  (= 
    (trigram  i really enjoy 129) True)
  (= 
    (trigram  i love his 129) True)
  (= 
    (trigram  'have,you,seen' the new 129) True)
  (= 
    (trigram  a good point 129) True)
  (= 
    (trigram  yeah i agree 128) True)
  (= 
    (trigram  too but i 128) True)
  (= 
    (trigram  i thought they 128) True)
  (= 
    (trigram  in this one 128) True)
  (= 
    (trigram  in this movie 128) True)
  (= 
    (trigram  had no idea 128) True)
  (= 
    (trigram  excited to see 128) True)
  (= 
    (trigram  about the new 128) True)
  (= 
    (trigram  yes i think 127) True)
  (= 
    (trigram  yeah they were 127) True)
  (= 
    (trigram  that he was 127) True)
  (= 
    (trigram  its about a 127) True)
  (= 
    (trigram  it has to 127) True)
  (= 
    (trigram  it a lot 127) True)
  (= 
    (trigram  is a lot 127) True)
  (= 
    (trigram  i grew up 127) True)
  (= 
    (trigram  have you watched 127) True)
  (= 
    (trigram  few years ago 127) True)
  (= 
    (trigram  are a lot 127) True)
  (= 
    (trigram  you mean by 126) True)
  (= 
    (trigram  yes i agree 126) True)
  (= 
    (trigram  wish i could 126) True)
  (= 
    (trigram  to have to 126) True)
  (= 
    (trigram  me about it 126) True)
  (= 
    (trigram  like i said 126) True)
  (= 
    (trigram  id like to 126) True)
  (= 
    (trigram  i believe it 126) True)
  (= 
    (trigram  do you prefer 126) True)
  (= 
    (trigram  but he was 126) True)
  (= 
    (trigram  yeah they are 125) True)
  (= 
    (trigram  what would you 125) True)
  (= 
    (trigram  that is one 125) True)
  (= 
    (trigram  really want to 125) True)
  (= 
    (trigram  i had no 125) True)
  (= 
    (trigram  i guess thats 125) True)
  (= 
    (trigram  i dont see 125) True)
  (= 
    (trigram  based on a 125) True)
  (= 
    (trigram  at the same 125) True)
  (= 
    (trigram  you mean like 124) True)
  (= 
    (trigram  you listened to 124) True)
  (= 
    (trigram  see the movie 124) True)
  (= 
    (trigram  like to listen 124) True)
  (= 
    (trigram  in the world 124) True)
  (= 
    (trigram  have to look 124) True)
  (= 
    (trigram  you know how 123) True)
  (= 
    (trigram  they are going 123) True)
  (= 
    (trigram  the new star 123) True)
  (= 
    (trigram  so many good 123) True)
  (= 
    (trigram  know what i 123) True)
  (= 
    (trigram  know but i 123) True)
  (= 
    (trigram  i agree but 123) True)
  (= 
    (trigram  whos your favorite 122) True)
  (= 
    (trigram  we will see 122) True)
  (= 
    (trigram  think he will 122) True)
  (= 
    (trigram  one with the 122) True)
  (= 
    (trigram  oh that is 122) True)
  (= 
    (trigram  not a fan 122) True)
  (= 
    (trigram  it was called 122) True)
  (= 
    (trigram  its about a 122) True)
  (= 
    (trigram  in the past 122) True)
  (= 
    (trigram  in the last 122) True)
  (= 
    (trigram  i dont see 122) True)
  (= 
    (trigram  i cant 'wait,to,see' 122) True)
  (= 
    (trigram  'i,cant,wait' to see 122) True)
  (= 
    (trigram  are the best 122) True)
  (= 
    (trigram  and he is 122) True)
  (= 
    (trigram  yeah thats a 121) True)
  (= 
    (trigram  to make it 121) True)
  (= 
    (trigram  so do you 121) True)
  (= 
    (trigram  see what you 121) True)
  (= 
    (trigram  seem to be 121) True)
  (= 
    (trigram  look it up 121) True)
  (= 
    (trigram  i also love 121) True)
  (= 
    (trigram  but i would 121) True)
  (= 
    (trigram  be the best 121) True)
  (= 
    (trigram  that would have 120) True)
  (= 
    (trigram  is that a 120) True)
  (= 
    (trigram  i see what 120) True)
  (= 
    (trigram  i really dont 120) True)
  (= 
    (trigram  i dont want 120) True)
  (= 
    (trigram  i dont have 120) True)
  (= 
    (trigram  i agree i 120) True)
  (= 
    (trigram  dont want to 120) True)
  (= 
    (trigram  a chance to 120) True)
  (= 
    (trigram  you had to 119) True)
  (= 
    (trigram  yeah i really 119) True)
  (= 
    (trigram  yeah i guess 119) True)
  (= 
    (trigram  think it would 119) True)
  (= 
    (trigram  they have been 119) True)
  (= 
    (trigram  thats true but 119) True)
  (= 
    (trigram  she was a 119) True)
  (= 
    (trigram  rock and roll 119) True)
  (= 
    (trigram  oh i know 119) True)
  (= 
    (trigram  not sure but 119) True)
  (= 
    (trigram  i saw a 119) True)
  (= 
    (trigram  he was so 119) True)
  (= 
    (trigram  he is so 119) True)
  (= 
    (trigram  hall of fame 119) True)
  (= 
    (trigram  and the furious 119) True)
  (= 
    (trigram  about the movie 119) True)
  (= 
    (trigram  you listening to 118) True)
  (= 
    (trigram  you like that 118) True)
  (= 
    (trigram  the main character 118) True)
  (= 
    (trigram  in real life 118) True)
  (= 
    (trigram  favorite song of 118) True)
  (= 
    (trigram  but there are 118) True)
  (= 
    (trigram  but i was 118) True)
  (= 
    (trigram  but he is 118) True)
  (= 
    (trigram  any good movies 118) True)
  (= 
    (trigram  yes i am 117) True)
  (= 
    (trigram  they will be 117) True)
  (= 
    (trigram  the dark side 117) True)
  (= 
    (trigram  the best part 117) True)
  (= 
    (trigram  that they are 117) True)
  (= 
    (trigram  so do you 117) True)
  (= 
    (trigram  so do i 117) True)
  (= 
    (trigram  quite a few 117) True)
  (= 
    (trigram  oh yes i 117) True)
  (= 
    (trigram  of all the 117) True)
  (= 
    (trigram  i was in 117) True)
  (= 
    (trigram  it was in 117) True)
  (= 
    (trigram  i mean i 117) True)
  (= 
    (trigram  i know and 117) True)
  (= 
    (trigram  'have,to,check' it out 117) True)
  (= 
    (trigram  dont know how 117) True)
  (= 
    (trigram  yeah i agree 116) True)
  (= 
    (trigram  well i dont 116) True)
  (= 
    (trigram  of the greatest 116) True)
  (= 
    (trigram  me too but 116) True)
  (= 
    (trigram  like the new 116) True)
  (= 
    (trigram  it is one 116) True)
  (= 
    (trigram  in a while 116) True)
  (= 
    (trigram  havent heard of 116) True)
  (= 
    (trigram  fast and the 116) True)
  (= 
    (trigram  because it was 116) True)
  (= 
    (trigram  'are,you,a' fan of 116) True)
  (= 
    (trigram  wow thats a 115) True)
  (= 
    (trigram  with all the 115) True)
  (= 
    (trigram  well i dont 115) True)
  (= 
    (trigram  that was pretty 115) True)
  (= 
    (trigram  of the song 115) True)
  (= 
    (trigram  i wanted to 115) True)
  (= 
    (trigram  in star wars 115) True)
  (= 
    (trigram  i had a 115) True)
  (= 
    (trigram  you never know 114) True)
  (= 
    (trigram  well it is 114) True)
  (= 
    (trigram  of the movies 114) True)
  (= 
    (trigram  of the caribbean 114) True)
  (= 
    (trigram  i see what 114) True)
  (= 
    (trigram  i like all 114) True)
  (= 
    (trigram  i know you 114) True)
  (= 
    (trigram  i heard they 114) True)
  (= 
    (trigram  yeah thats the 113) True)
  (= 
    (trigram  that they are 113) True)
  (= 
    (trigram  oh my god 113) True)
  (= 
    (trigram  of the year 113) True)
  (= 
    (trigram  like about it 113) True)
  (= 
    (trigram  it is about 113) True)
  (= 
    (trigram  ill check it 113) True)
  (= 
    (trigram  if you had 113) True)
  (= 
    (trigram  hey did you 113) True)
  (= 
    (trigram  else do you 113) True)
  (= 
    (trigram  do they have 113) True)
  (= 
    (trigram  do not know 113) True)
  (= 
    (trigram  are you into 113) True)
  (= 
    (trigram  yes he did 112) True)
  (= 
    (trigram  yeah that one 112) True)
  (= 
    (trigram  yeah i do 112) True)
  (= 
    (trigram  they are going 112) True)
  (= 
    (trigram  of the first 112) True)
  (= 
    (trigram  i think theyre 112) True)
  (= 
    (trigram  i guess they 112) True)
  (= 
    (trigram  he did a 112) True)
  (= 
    (trigram  dont like the 112) True)
  (= 
    (trigram  be a great 112) True)
  (= 
    (trigram  well it was 111) True)
  (= 
    (trigram  to see what 111) True)
  (= 
    (trigram  seen any of 111) True)
  (= 
    (trigram  i thought so 111) True)
  (= 
    (trigram  i love how 111) True)
  (= 
    (trigram  i can understand 111) True)
  (= 
    (trigram  hard to say 111) True)
  (= 
    (trigram  good but i 111) True)
  (= 
    (trigram  and it is 111) True)
  (= 
    (trigram  you like them 110) True)
  (= 
    (trigram  yeah but i 110) True)
  (= 
    (trigram  would you like 110) True)
  (= 
    (trigram  was a lot 110) True)
  (= 
    (trigram  to the super 110) True)
  (= 
    (trigram  to say the 110) True)
  (= 
    (trigram  ok i will 110) True)
  (= 
    (trigram  no not really 110) True)
  (= 
    (trigram  ive been listening 110) True)
  (= 
    (trigram  it was released 110) True)
  (= 
    (trigram  it should be 110) True)
  (= 
    (trigram  its a shame 110) True)
  (= 
    (trigram  it any good 110) True)
  (= 
    (trigram  i really want 110) True)
  (= 
    (trigram  i get that 110) True)
  (= 
    (trigram  favorite song from 110) True)
  (= 
    (trigram  a great actor 110) True)
  (= 
    (trigram  you been listening 109) True)
  (= 
    (trigram  yes i saw 109) True)
  (= 
    (trigram  yeah i heard 109) True)
  (= 
    (trigram  to come out 109) True)
  (= 
    (trigram  they are so 109) True)
  (= 
    (trigram  that is what 109) True)
  (= 
    (trigram  in the movies 109) True)
  (= 
    (trigram  going to go 109) True)
  (= 
    (trigram  going to do 109) True)
  (= 
    (trigram  but i cant 109) True)
  (= 
    (trigram  all of his 109) True)
  (= 
    (trigram  you mean like 108) True)
  (= 
    (trigram  yeah thats the 108) True)
  (= 
    (trigram  would be the 108) True)
  (= 
    (trigram  who would you 108) True)
  (= 
    (trigram  to do that 108) True)
  (= 
    (trigram  think i would 108) True)
  (= 
    (trigram  the way he 108) True)
  (= 
    (trigram  team in the 108) True)
  (= 
    (trigram  on that one 108) True)
  (= 
    (trigram  of the time 108) True)
  (= 
    (trigram  movie of all 108) True)
  (= 
    (trigram  make it to 108) True)
  (= 
    (trigram  i was so 108) True)
  (= 
    (trigram  it is very 108) True)
  (= 
    (trigram  i think a 108) True)
  (= 
    (trigram  is hard to 108) True)
  (= 
    (trigram  is a very 108) True)
  (= 
    (trigram  i really dont 108) True)
  (= 
    (trigram  in high school 108) True)
  (= 
    (trigram  huge fan of 108) True)
  (= 
    (trigram  get to see 108) True)
  (= 
    (trigram  dont know what 108) True)
  (= 
    (trigram  you know the 107) True)
  (= 
    (trigram  yes he did 107) True)
  (= 
    (trigram  well that is 107) True)
  (= 
    (trigram  watch it again 107) True)
  (= 
    (trigram  to win the 107) True)
  (= 
    (trigram  they are the 107) True)
  (= 
    (trigram  out in the 107) True)
  (= 
    (trigram  like the beatles 107) True)
  (= 
    (trigram  it was awesome 107) True)
  (= 
    (trigram  ill 'have,to,check' it 107) True)
  (= 
    (trigram  but i love 107) True)
  (= 
    (trigram  and they are 107) True)
  (= 
    (trigram  what is a 106) True)
  (= 
    (trigram  up with the 106) True)
  (= 
    (trigram  they are the 106) True)
  (= 
    (trigram  the way they 106) True)
  (= 
    (trigram  of the band 106) True)
  (= 
    (trigram  no not really 106) True)
  (= 
    (trigram  i would be 106) True)
  (= 
    (trigram  it is not 106) True)
  (= 
    (trigram  i remember the 106) True)
  (= 
    (trigram  in terms of 106) True)
  (= 
    (trigram  i like their 106) True)
  (= 
    (trigram  how can you 106) True)
  (= 
    (trigram  had a great 106) True)
  (= 
    (trigram  but im not 106) True)
  (= 
    (trigram  as far as 106) True)
  (= 
    (trigram  are you excited 106) True)
  (= 
    (trigram  would be cool 105) True)
  (= 
    (trigram  who was in 105) True)
  (= 
    (trigram  when they were 105) True)
  (= 
    (trigram  were going to 105) True)
  (= 
    (trigram  went to the 105) True)
  (= 
    (trigram  well i like 105) True)
  (= 
    (trigram  was good but 105) True)
  (= 
    (trigram  the last movie 105) True)
  (= 
    (trigram  that you like 105) True)
  (= 
    (trigram  so what is 105) True)
  (= 
    (trigram  should watch it 105) True)
  (= 
    (trigram  out with a 105) True)
  (= 
    (trigram  know if i 105) True)
  (= 
    (trigram  it was an 105) True)
  (= 
    (trigram  i guess we 105) True)
  (= 
    (trigram  i cant remember 105) True)
  (= 
    (trigram  i also liked 105) True)
  (= 
    (trigram  for a long 105) True)
  (= 
    (trigram  are you kidding 105) True)
  (= 
    (trigram  you like the 104) True)
  (= 
    (trigram  who is that 104) True)
  (= 
    (trigram  what are they 104) True)
  (= 
    (trigram  they have the 104) True)
  (= 
    (trigram  oh that is 104) True)
  (= 
    (trigram  of the other 104) True)
  (= 
    (trigram  it is but 104) True)
  (= 
    (trigram  in the theater 104) True)
  (= 
    (trigram  in the next 104) True)
  (= 
    (trigram  i love him 104) True)
  (= 
    (trigram  i didnt think 104) True)
  (= 
    (trigram  for some reason 104) True)
  (= 
    (trigram  a tough one 104) True)
  (= 
    (trigram  yes she is 103) True)
  (= 
    (trigram  we should go 103) True)
  (= 
    (trigram  to the superbowl 103) True)
  (= 
    (trigram  that is what 103) True)
  (= 
    (trigram  that could be 103) True)
  (= 
    (trigram  remember that one 103) True)
  (= 
    (trigram  quite a bit 103) True)
  (= 
    (trigram  oh my god 103) True)
  (= 
    (trigram  not going to 103) True)
  (= 
    (trigram  my favorite part 103) True)
  (= 
    (trigram  maybe i will 103) True)
  (= 
    (trigram  it was amazing 103) True)
  (= 
    (trigram  its a shame 103) True)
  (= 
    (trigram  im not really 103) True)
  (= 
    (trigram  i love all 103) True)
  (= 
    (trigram  i heard he 103) True)
  (= 
    (trigram  i didnt see 103) True)
  (= 
    (trigram  have you listened 103) True)
  (= 
    (trigram  got to be 103) True)
  (= 
    (trigram  be in the 103) True)
  (= 
    (trigram  yes that one 102) True)
  (= 
    (trigram  well i think 102) True)
  (= 
    (trigram  well i guess 102) True)
  (= 
    (trigram  wait for the 102) True)
  (= 
    (trigram  they used to 102) True)
  (= 
    (trigram  that is so 102) True)
  (= 
    (trigram  ok i will 102) True)
  (= 
    (trigram  not sure i 102) True)
  (= 
    (trigram  like to watch 102) True)
  (= 
    (trigram  it was in 102) True)
  (= 
    (trigram  i think ive 102) True)
  (= 
    (trigram  it has been 102) True)
  (= 
    (trigram  is the one 102) True)
  (= 
    (trigram  in the new 102) True)
  (= 
    (trigram  i never thought 102) True)
  (= 
    (trigram  i know and 102) True)
  (= 
    (trigram  i dont have 102) True)
  (= 
    (trigram  he has been 102) True)
  (= 
    (trigram  harry potter movies 102) True)
  (= 
    (trigram  game last night 102) True)
  (= 
    (trigram  ever been to 102) True)
  (= 
    (trigram  a good idea 102) True)
  (= 
    (trigram  yes thats the 101) True)
  (= 
    (trigram  the last time 101) True)
  (= 
    (trigram  make the playoffs 101) True)
  (= 
    (trigram  like a good 101) True)
  (= 
    (trigram  it had a 101) True)
  (= 
    (trigram  going to win 101) True)
  (= 
    (trigram  you ready for 100) True)
  (= 
    (trigram  yeah its a 100) True)
  (= 
    (trigram  yeah i have 100) True)
  (= 
    (trigram  why did you 100) True)
  (= 
    (trigram  was a big 100) True)
  (= 
    (trigram  the way they 100) True)
  (= 
    (trigram  thats too bad 100) True)
  (= 
    (trigram  some of it 100) True)
  (= 
    (trigram  some of her 100) True)
  (= 
    (trigram  of that one 100) True)
  (= 
    (trigram  of her songs 100) True)
  (= 
    (trigram  not a big 100) True)
  (= 
    (trigram  no it was 100) True)
  (= 
    (trigram  no but i 100) True)
  (= 
    (trigram  listen to a 100) True)
  (= 
    (trigram  listening to the 100) True)
  (= 
    (trigram  i will be 100) True)
  (= 
    (trigram  it was one 100) True)
  (= 
    (trigram  i heard the 100) True)
  (= 
    (trigram  id love to 100) True)
  (= 
    (trigram  i did too 100) True)
  (= 
    (trigram  how about you 100) True)
  (= 
    (trigram  havent seen it 100) True)
  (= 
    (trigram  have not seen 100) True)
  (= 
    (trigram  but if you 100) True)
  (= 
    (trigram  are you serious 100) True)
  (= 
    (trigram  was a pretty 99) True)
  (= 
    (trigram  oh my gosh 99) True)
  (= 
    (trigram  of the original 99) True)
  (= 
    (trigram  of them are 99) True)
  (= 
    (trigram  me want to 99) True)
  (= 
    (trigram  i will check 99) True)
  (= 
    (trigram  ive never seen 99) True)
  (= 
    (trigram  it might be 99) True)
  (= 
    (trigram  is a little 99) True)
  (= 
    (trigram  in the same 99) True)
  (= 
    (trigram  i heard they 99) True)
  (= 
    (trigram  'have,you,ever' heard of 99) True)
  (= 
    (trigram  and of course 99) True)
  (= 
    (trigram  and he was 99) True)
  (= 
    (trigram  and he is 99) True)
  (= 
    (trigram  yes she is 98) True)
  (= 
    (trigram  yeah i was 98) True)
  (= 
    (trigram  will have a 98) True)
  (= 
    (trigram  well it is 98) True)
  (= 
    (trigram  was great in 98) True)
  (= 
    (trigram  they are great 98) True)
  (= 
    (trigram  the only one 98) True)
  (= 
    (trigram  the new beauty 98) True)
  (= 
    (trigram  the lead singer 98) True)
  (= 
    (trigram  the guy who 98) True)
  (= 
    (trigram  that was one 98) True)
  (= 
    (trigram  sounds like it 98) True)
  (= 
    (trigram  really liked it 98) True)
  (= 
    (trigram  i love those 98) True)
  (= 
    (trigram  i know you 98) True)
  (= 
    (trigram  i bet it 98) True)
  (= 
    (trigram  black and white 98) True)
  (= 
    (trigram  been to a 98) True)
  (= 
    (trigram  are your favorite 98) True)
  (= 
    (trigram  are you listening 98) True)
  (= 
    (trigram  and i love 98) True)
  (= 
    (trigram  you ever been 97) True)
  (= 
    (trigram  yeah they were 97) True)
  (= 
    (trigram  yeah i can 97) True)
  (= 
    (trigram  think ive heard 97) True)
  (= 
    (trigram  that was really 97) True)
  (= 
    (trigram  so what is 97) True)
  (= 
    (trigram  seen it yet 97) True)
  (= 
    (trigram  i guess youre 97) True)
  (= 
    (trigram  he was great 97) True)
  (= 
    (trigram  have never heard 97) True)
  (= 
    (trigram  for the new 97) True)
  (= 
    (trigram  but i cant 97) True)
  (= 
    (trigram  bit of a 97) True)
  (= 
    (trigram  you should watch 96) True)
  (= 
    (trigram  yes they were 96) True)
  (= 
    (trigram  up in the 96) True)
  (= 
    (trigram  to say that 96) True)
  (= 
    (trigram  they are all 96) True)
  (= 
    (trigram  the whole movie 96) True)
  (= 
    (trigram  the special effects 96) True)
  (= 
    (trigram  one of her 96) True)
  (= 
    (trigram  of the game 96) True)
  (= 
    (trigram  of the beatles 96) True)
  (= 
    (trigram  listen to some 96) True)
  (= 
    (trigram  i think this 96) True)
  (= 
    (trigram  it but i 96) True)
  (= 
    (trigram  i like his 96) True)
  (= 
    (trigram  i know a 96) True)
  (= 
    (trigram  i also love 96) True)
  (= 
    (trigram  going to watch 96) True)
  (= 
    (trigram  ever see the 96) True)
  (= 
    (trigram  dont think it 96) True)
  (= 
    (trigram  dont think he 96) True)
  (= 
    (trigram  because it was 96) True)
  (= 
    (trigram  all of his 96) True)
  (= 
    (trigram  you think was 95) True)
  (= 
    (trigram  you know it 95) True)
  (= 
    (trigram  yes thats the 95) True)
  (= 
    (trigram  yeah i do 95) True)
  (= 
    (trigram  yeah but it 95) True)
  (= 
    (trigram  will be in 95) True)
  (= 
    (trigram  want to be 95) True)
  (= 
    (trigram  up with the 95) True)
  (= 
    (trigram  this is the 95) True)
  (= 
    (trigram  this is a 95) True)
  (= 
    (trigram  thats true but 95) True)
  (= 
    (trigram  that sounds great 95) True)
  (= 
    (trigram  that sounds good 95) True)
  (= 
    (trigram  song do you 95) True)
  (= 
    (trigram  oh thats a 95) True)
  (= 
    (trigram  oh my gosh 95) True)
  (= 
    (trigram  new beauty and 95) True)
  (= 
    (trigram  i was really 95) True)
  (= 
    (trigram  it was about 95) True)
  (= 
    (trigram  i think this 95) True)
  (= 
    (trigram  it comes out 95) True)
  (= 
    (trigram  if i had 95) True)
  (= 
    (trigram  he is one 95) True)
  (= 
    (trigram  have a chance 95) True)
  (= 
    (trigram  but i know 95) True)
  (= 
    (trigram  yes and i 94) True)
  (= 
    (trigram  they should have 94) True)
  (= 
    (trigram  sure but i 94) True)
  (= 
    (trigram  so many great 94) True)
  (= 
    (trigram  my favorite character 94) True)
  (= 
    (trigram  love the song 94) True)
  (= 
    (trigram  lot of great 94) True)
  (= 
    (trigram  listen to music 94) True)
  (= 
    (trigram  know it was 94) True)
  (= 
    (trigram  'is,that,the' one with 94) True)
  (= 
    (trigram  is so good 94) True)
  (= 
    (trigram  i dont even 94) True)
  (= 
    (trigram  'have,you,ever' seen the 94) True)
  (= 
    (trigram  have to admit 94) True)
  (= 
    (trigram  both of them 94) True)
  (= 
    (trigram  all time favorite 94) True)
  (= 
    (trigram  you ever watch 93) True)
  (= 
    (trigram  was on the 93) True)
  (= 
    (trigram  there is no 93) True)
  (= 
    (trigram  the other night 93) True)
  (= 
    (trigram  the new movie 93) True)
  (= 
    (trigram  that was so 93) True)
  (= 
    (trigram  that he is 93) True)
  (= 
    (trigram  should check out 93) True)
  (= 
    (trigram  much of a 93) True)
  (= 
    (trigram  me too but 93) True)
  (= 
    (trigram  i did like 93) True)
  (= 
    (trigram  but i was 93) True)
  (= 
    (trigram  would be awesome 92) True)
  (= 
    (trigram  wish they would 92) True)
  (= 
    (trigram  win it all 92) True)
  (= 
    (trigram  well at least 92) True)
  (= 
    (trigram  was the name 92) True)
  (= 
    (trigram  was released in 92) True)
  (= 
    (trigram  think they can 92) True)
  (= 
    (trigram  the last jedi 92) True)
  (= 
    (trigram  that was an 92) True)
  (= 
    (trigram  that but i 92) True)
  (= 
    (trigram  talking about the 92) True)
  (= 
    (trigram  she was in 92) True)
  (= 
    (trigram  not know that 92) True)
  (= 
    (trigram  i wonder why 92) True)
  (= 
    (trigram  it was okay 92) True)
  (= 
    (trigram  it was like 92) True)
  (= 
    (trigram  it kind of 92) True)
  (= 
    (trigram  it comes to 92) True)
  (= 
    (trigram  it all the 92) True)
  (= 
    (trigram  i guess the 92) True)
  (= 
    (trigram  i dont even 92) True)
  (= 
    (trigram  i always thought 92) True)
  (= 
    (trigram  he is in 92) True)
  (= 
    (trigram  are you doing 92) True)
  (= 
    (trigram  yes i like 91) True)
  (= 
    (trigram  well that is 91) True)
  (= 
    (trigram  think you are 91) True)
  (= 
    (trigram  think will win 91) True)
  (= 
    (trigram  think its a 91) True)
  (= 
    (trigram  they have some 91) True)
  (= 
    (trigram  they are still 91) True)
  (= 
    (trigram  the empire strikes 91) True)
  (= 
    (trigram  the dark side 91) True)
  (= 
    (trigram  most of them 91) True)
  (= 
    (trigram  like i said 91) True)
  (= 
    (trigram  it was not 91) True)
  (= 
    (trigram  have to listen 91) True)
  (= 
    (trigram  had so many 91) True)
  (= 
    (trigram  came out with 91) True)
  (= 
    (trigram  are you ready 91) True)
  (= 
    (trigram  are you looking 91) True)
  (= 
    (trigram  a lot about 91) True)
  (= 
    (trigram  about that one 91) True)
  (= 
    (trigram  you on that 90) True)
  (= 
    (trigram  which is your 90) True)
  (= 
    (trigram  'what,kind,of' 'music,do,you' like 90) True)
  (= 
    (trigram  think she is 90) True)
  (= 
    (trigram  they are really 90) True)
  (= 
    (trigram  they are good 90) True)
  (= 
    (trigram  the movie the 90) True)
  (= 
    (trigram  the dark knight 90) True)
  (= 
    (trigram  that will be 90) True)
  (= 
    (trigram  that is not 90) True)
  (= 
    (trigram  talk about music 90) True)
  (= 
    (trigram  should be a 90) True)
  (= 
    (trigram  oh i think 90) True)
  (= 
    (trigram  it is hard 90) True)
  (= 
    (trigram  in the series 90) True)
  (= 
    (trigram  in the film 90) True)
  (= 
    (trigram  interesting to see 90) True)
  (= 
    (trigram  ill have to 90) True)
  (= 
    (trigram  i heard he 90) True)
  (= 
    (trigram  i feel the 90) True)
  (= 
    (trigram  i didnt see 90) True)
  (= 
    (trigram  i completely agree 90) True)
  (= 
    (trigram  are in the 90) True)
  (= 
    (trigram  and i dont 90) True)
  (= 
    (trigram  you think so 89) True)
  (= 
    (trigram  yeah i love 89) True)
  (= 
    (trigram  yeah but he 89) True)
  (= 
    (trigram  with you on 89) True)
  (= 
    (trigram  will win the 89) True)
  (= 
    (trigram  who are they 89) True)
  (= 
    (trigram  was so funny 89) True)
  (= 
    (trigram  think i know 89) True)
  (= 
    (trigram  them in concert 89) True)
  (= 
    (trigram  that you like 89) True)
  (= 
    (trigram  that is an 89) True)
  (= 
    (trigram  that he is 89) True)
  (= 
    (trigram  really like that 89) True)
  (= 
    (trigram  over the top 89) True)
  (= 
    (trigram  maybe i will 89) True)
  (= 
    (trigram  like the movie 89) True)
  (= 
    (trigram  is the greatest 89) True)
  (= 
    (trigram  im a big 89) True)
  (= 
    (trigram  i know a 89) True)
  (= 
    (trigram  i dont care 89) True)
  (= 
    (trigram  hes a great 89) True)
  (= 
    (trigram  heard the new 89) True)
  (= 
    (trigram  guess youre right 89) True)
  (= 
    (trigram  your favorite band 88) True)
  (= 
    (trigram  you hear that 88) True)
  (= 
    (trigram  yeah but they 88) True)
  (= 
    (trigram  were going to 88) True)
  (= 
    (trigram  think they were 88) True)
  (= 
    (trigram  the best of 88) True)
  (= 
    (trigram  of his movies 88) True)
  (= 
    (trigram  no i think 88) True)
  (= 
    (trigram  my favorite movies 88) True)
  (= 
    (trigram  listen to that 88) True)
  (= 
    (trigram  like the most 88) True)
  (= 
    (trigram  i would go 88) True)
  (= 
    (trigram  i watched the 88) True)
  (= 
    (trigram  it was kind 88) True)
  (= 
    (trigram  is the name 88) True)
  (= 
    (trigram  in a way 88) True)
  (= 
    (trigram  in a lot 88) True)
  (= 
    (trigram  i listened to 88) True)
  (= 
    (trigram  i have the 88) True)
  (= 
    (trigram  i bet that 88) True)
  (= 
    (trigram  have to do 88) True)
  (= 
    (trigram  a very good 88) True)
  (= 
    (trigram  and i dont 88) True)
  (= 
    (trigram  a disney movie 88) True)
  (= 
    (trigram  you see it 87) True)
  (= 
    (trigram  you know they 87) True)
  (= 
    (trigram  you hear about 87) True)
  (= 
    (trigram  yes i remember 87) True)
  (= 
    (trigram  wow that sounds 87) True)
  (= 
    (trigram  what i mean 87) True)
  (= 
    (trigram  well if you 87) True)
  (= 
    (trigram  to see her 87) True)
  (= 
    (trigram  to get a 87) True)
  (= 
    (trigram  they could have 87) True)
  (= 
    (trigram  theres a lot 87) True)
  (= 
    (trigram  that it is 87) True)
  (= 
    (trigram  one is your 87) True)
  (= 
    (trigram  lot of fun 87) True)
  (= 
    (trigram  know that one 87) True)
  (= 
    (trigram  know a lot 87) True)
  (= 
    (trigram  its kind of 87) True)
  (= 
    (trigram  it depends on 87) True)
  (= 
    (trigram  i remember when 87) True)
  (= 
    (trigram  in real life 87) True)
  (= 
    (trigram  i hope he 87) True)
  (= 
    (trigram  i am glad 87) True)
  (= 
    (trigram  he is so 87) True)
  (= 
    (trigram  have heard that 87) True)
  (= 
    (trigram  had a good 87) True)
  (= 
    (trigram  genre of music 87) True)
  (= 
    (trigram  feel the same 87) True)
  (= 
    (trigram  but i guess 87) True)
  (= 
    (trigram  but i didnt 87) True)
  (= 
    (trigram  but i also 87) True)
  (= 
    (trigram  your favorite album 86) True)
  (= 
    (trigram  you know it 86) True)
  (= 
    (trigram  you go to 86) True)
  (= 
    (trigram  yes they were 86) True)
  (= 
    (trigram  yeah i thought 86) True)
  (= 
    (trigram  yeah and the 86) True)
  (= 
    (trigram  what makes you 86) True)
  (= 
    (trigram  'what,is,your' favorite song 86) True)
  (= 
    (trigram  what does that 86) True)
  (= 
    (trigram  well at least 86) True)
  (= 
    (trigram  think my favorite 86) True)
  (= 
    (trigram  they were a 86) True)
  (= 
    (trigram  the top of 86) True)
  (= 
    (trigram  the story line 86) True)
  (= 
    (trigram  on the album 86) True)
  (= 
    (trigram  of his music 86) True)
  (= 
    (trigram  jar jar binks 86) True)
  (= 
    (trigram  'is,one,of' the best 86) True)
  (= 
    (trigram  is a bit 86) True)
  (= 
    (trigram  i remember the 86) True)
  (= 
    (trigram  i just love 86) True)
  (= 
    (trigram  i cant remember 86) True)
  (= 
    (trigram  for the most 86) True)
  (= 
    (trigram  do this year 86) True)
  (= 
    (trigram  dont know how 86) True)
  (= 
    (trigram  didnt like it 86) True)
  (= 
    (trigram  could have been 86) True)
  (= 
    (trigram  character in the 86) True)
  (= 
    (trigram  you dont think 85) True)
  (= 
    (trigram  you been to 85) True)
  (= 
    (trigram  yeah that is 85) True)
  (= 
    (trigram  why dont you 85) True)
  (= 
    (trigram  the scene where 85) True)
  (= 
    (trigram  thats my favorite 85) True)
  (= 
    (trigram  thats a great 85) True)
  (= 
    (trigram  team do you 85) True)
  (= 
    (trigram  seen it yet 85) True)
  (= 
    (trigram  of the season 85) True)
  (= 
    (trigram  of movies do 85) True)
  (= 
    (trigram  not really i 85) True)
  (= 
    (trigram  my favorite movie 85) True)
  (= 
    (trigram  its a great 85) True)
  (= 
    (trigram  i think youre 85) True)
  (= 
    (trigram  it can be 85) True)
  (= 
    (trigram  im pretty sure 85) True)
  (= 
    (trigram  i hope it 85) True)
  (= 
    (trigram  i heard about 85) True)
  (= 
    (trigram  'how,do,you' feel about 85) True)
  (= 
    (trigram  hey what do 85) True)
  (= 
    (trigram  he is very 85) True)
  (= 
    (trigram  hall of fame 85) True)
  (= 
    (trigram  dont think ive 85) True)
  (= 
    (trigram  dont know but 85) True)
  (= 
    (trigram  did not like 85) True)
  (= 
    (trigram  all kinds of 85) True)
  (= 
    (trigram  a little more 85) True)
  (= 
    (trigram  a great voice 85) True)
  (= 
    (trigram  a good team 85) True)
  (= 
    (trigram  yes of course 84) True)
  (= 
    (trigram  yes and the 84) True)
  (= 
    (trigram  used to love 84) True)
  (= 
    (trigram  to make the 84) True)
  (= 
    (trigram  them in the 84) True)
  (= 
    (trigram  thats why i 84) True)
  (= 
    (trigram  thanks for the 84) True)
  (= 
    (trigram  some of my 84) True)
  (= 
    (trigram  of it is 84) True)
  (= 
    (trigram  just saw the 84) True)
  (= 
    (trigram  is there a 84) True)
  (= 
    (trigram  i love their 84) True)
  (= 
    (trigram  you like him 83) True)
  (= 
    (trigram  yes that one 83) True)
  (= 
    (trigram  will be good 83) True)
  (= 
    (trigram  will always be 83) True)
  (= 
    (trigram  why did you 83) True)
  (= 
    (trigram  what it is 83) True)
  (= 
    (trigram  well i am 83) True)
  (= 
    (trigram  was supposed to 83) True)
  (= 
    (trigram  to a game 83) True)
  (= 
    (trigram  they are pretty 83) True)
  (= 
    (trigram  the rolling stones 83) True)
  (= 
    (trigram  there will be 83) True)
  (= 
    (trigram  there were a 83) True)
  (= 
    (trigram  seems like a 83) True)
  (= 
    (trigram  oh yeah that 83) True)
  (= 
    (trigram  look forward to 83) True)
  (= 
    (trigram  look at the 83) True)
  (= 
    (trigram  its been a 83) True)
  (= 
    (trigram  it really was 83) True)
  (= 
    (trigram  it is called 83) True)
  (= 
    (trigram  i think im 83) True)
  (= 
    (trigram  i saw them 83) True)
  (= 
    (trigram  in my head 83) True)
  (= 
    (trigram  i do think 83) True)
  (= 
    (trigram  have been listening 83) True)
  (= 
    (trigram  hard to believe 83) True)
  (= 
    (trigram  dont you think 83) True)
  (= 
    (trigram  dont have to 83) True)
  (= 
    (trigram  didnt like the 83) True)
  (= 
    (trigram  but i just 83) True)
  (= 
    (trigram  a tough question 83) True)
  (= 
    (trigram  yes i know 82) True)
  (= 
    (trigram  yes but it 82) True)
  (= 
    (trigram  yeah but the 82) True)
  (= 
    (trigram  wonder if they 82) True)
  (= 
    (trigram  who else is 82) True)
  (= 
    (trigram  well they are 82) True)
  (= 
    (trigram  to see if 82) True)
  (= 
    (trigram  that sounds interesting 82) True)
  (= 
    (trigram  thats kind of 82) True)
  (= 
    (trigram  oh thats right 82) True)
  (= 
    (trigram  my favorite songs 82) True)
  (= 
    (trigram  interesting to see 82) True)
  (= 
    (trigram  i hope the 82) True)
  (= 
    (trigram  i doubt it 82) True)
  (= 
    (trigram  i didnt really 82) True)
  (= 
    (trigram  hes one of 82) True)
  (= 
    (trigram  heard it was 82) True)
  (= 
    (trigram  had to pick 82) True)
  (= 
    (trigram  'do,you,think' they will 82) True)
  (= 
    (trigram  dont know why 82) True)
  (= 
    (trigram  but you know 82) True)
  (= 
    (trigram  but what about 82) True)
  (= 
    (trigram  are really good 82) True)
  (= 
    (trigram  a new hope 82) True)
  (= 
    (trigram  a bit more 82) True)
  (= 
    (trigram  your favorite scene 81) True)
  (= 
    (trigram  yes of course 81) True)
  (= 
    (trigram  yes i loved 81) True)
  (= 
    (trigram  yes but i 81) True)
  (= 
    (trigram  want to hear 81) True)
  (= 
    (trigram  wanted to see 81) True)
  (= 
    (trigram  true but i 81) True)
  (= 
    (trigram  they had to 81) True)
  (= 
    (trigram  the edge of 81) True)
  (= 
    (trigram  that the movie 81) True)
  (= 
    (trigram  of that movie 81) True)
  (= 
    (trigram  know about that 81) True)
  (= 
    (trigram  its such a 81) True)
  (= 
    (trigram  is better than 81) True)
  (= 
    (trigram  in the super 81) True)
  (= 
    (trigram  in the mood 81) True)
  (= 
    (trigram  i never saw 81) True)
  (= 
    (trigram  i liked how 81) True)
  (= 
    (trigram  'have,you,been' listening to 81) True)
  (= 
    (trigram  good movies lately 81) True)
  (= 
    (trigram  dont like the 81) True)
  (= 
    (trigram  but if you 81) True)
  (= 
    (trigram  believe it was 81) True)
  (= 
    (trigram  a good actor 81) True)
  (= 
    (trigram  you could say 80) True)
  (= 
    (trigram  yea it was 80) True)
  (= 
    (trigram  thought they were 80) True)
  (= 
    (trigram  the story line 80) True)
  (= 
    (trigram  the music is 80) True)
  (= 
    (trigram  the best in 80) True)
  (= 
    (trigram  song on the 80) True)
  (= 
    (trigram  so it was 80) True)
  (= 
    (trigram  so i guess 80) True)
  (= 
    (trigram  over the years 80) True)
  (= 
    (trigram  let you know 80) True)
  (= 
    (trigram  i sure hope 80) True)
  (= 
    (trigram  'is,one,of' my favorite 80) True)
  (= 
    (trigram  i bet that 80) True)
  (= 
    (trigram  i bet it 80) True)
  (= 
    (trigram  has the best 80) True)
  (= 
    (trigram  had to be 80) True)
  (= 
    (trigram  from the movie 80) True)
  (= 
    (trigram  first one was 80) True)
  (= 
    (trigram  dont think ive 80) True)
  (= 
    (trigram  did you have 80) True)
  (= 
    (trigram  definitely one of 80) True)
  (= 
    (trigram  come out with 80) True)
  (= 
    (trigram  can you believe 80) True)
  (= 
    (trigram  can understand that 80) True)
  (= 
    (trigram  but they have 80) True)
  (= 
    (trigram  because it is 80) True)
  (= 
    (trigram  are my favorite 80) True)
  (= 
    (trigram  yeah thats true 79) True)
  (= 
    (trigram  yeah i am 79) True)
  (= 
    (trigram  what you think 79) True)
  (= 
    (trigram  we will have 79) True)
  (= 
    (trigram  to do it 79) True)
  (= 
    (trigram  they would have 79) True)
  (= 
    (trigram  they were so 79) True)
  (= 
    (trigram  they are not 79) True)
  (= 
    (trigram  they are both 79) True)
  (= 
    (trigram  that they have 79) True)
  (= 
    (trigram  that is why 79) True)
  (= 
    (trigram  of their music 79) True)
  (= 
    (trigram  not so much 79) True)
  (= 
    (trigram  not really a 79) True)
  (= 
    (trigram  no i have 79) True)
  (= 
    (trigram  maybe we can 79) True)
  (= 
    (trigram  like to go 79) True)
  (= 
    (trigram  it is pretty 79) True)
  (= 
    (trigram  i guess the 79) True)
  (= 
    (trigram  i agree it 79) True)
  (= 
    (trigram  he used to 79) True)
  (= 
    (trigram  has been a 79) True)
  (= 
    (trigram  first came out 79) True)
  (= 
    (trigram  excited for the 79) True)
  (= 
    (trigram  do you enjoy 79) True)
  (= 
    (trigram  could be a 79) True)
  (= 
    (trigram  but they were 79) True)
  (= 
    (trigram  are one of 79) True)
  (= 
    (trigram  a new one 79) True)
  (= 
    (trigram  a great idea 79) True)
  (= 
    (trigram  you know if 78) True)
  (= 
    (trigram  yes they did 78) True)
  (= 
    (trigram  yeah that one 78) True)
  (= 
    (trigram  would say the 78) True)
  (= 
    (trigram  'what,did,you' think about 78) True)
  (= 
    (trigram  to one of 78) True)
  (= 
    (trigram  they made a 78) True)
  (= 
    (trigram  that was an 78) True)
  (= 
    (trigram  on the field 78) True)
  (= 
    (trigram  oh me too 78) True)
  (= 
    (trigram  of the star 78) True)
  (= 
    (trigram  of the music 78) True)
  (= 
    (trigram  not sure what 78) True)
  (= 
    (trigram  not sure but 78) True)
  (= 
    (trigram  much better than 78) True)
  (= 
    (trigram  know much about 78) True)
  (= 
    (trigram  just like the 78) True)
  (= 
    (trigram  i really loved 78) True)
  (= 
    (trigram  i hear you 78) True)
  (= 
    (trigram  i didnt realize 78) True)
  (= 
    (trigram  come up with 78) True)
  (= 
    (trigram  are your thoughts 78) True)
  (= 
    (trigram  and they were 78) True)
  (= 
    (trigram  a lot to 78) True)
  (= 
    (trigram  yeah and the 77) True)
  (= 
    (trigram  was just a 77) True)
  (= 
    (trigram  to watch a 77) True)
  (= 
    (trigram  the music video 77) True)
  (= 
    (trigram  the most part 77) True)
  (= 
    (trigram  that song was 77) True)
  (= 
    (trigram  that might be 77) True)
  (= 
    (trigram  so you think 77) True)
  (= 
    (trigram  so much more 77) True)
  (= 
    (trigram  right about that 77) True)
  (= 
    (trigram  lot of money 77) True)
  (= 
    (trigram  listening to a 77) True)
  (= 
    (trigram  i wouldnt say 77) True)
  (= 
    (trigram  it was on 77) True)
  (= 
    (trigram  i think shes 77) True)
  (= 
    (trigram  i think of 77) True)
  (= 
    (trigram  i might have 77) True)
  (= 
    (trigram  if they are 77) True)
  (= 
    (trigram  i cant stand 77) True)
  (= 
    (trigram  has a good 77) True)
  (= 
    (trigram  are a few 77) True)
  (= 
    (trigram  any of them 77) True)
  (= 
    (trigram  also like the 77) True)
  (= 
    (trigram  a little too 77) True)
  (= 
    (trigram  your least favorite 76) True)
  (= 
    (trigram  your favorite genre 76) True)
  (= 
    (trigram  you didnt like 76) True)
  (= 
    (trigram  yes i really 76) True)
  (= 
    (trigram  yes he does 76) True)
  (= 
    (trigram  yes and the 76) True)
  (= 
    (trigram  where did you 76) True)
  (= 
    (trigram  when it came 76) True)
  (= 
    (trigram  was in that 76) True)
  (= 
    (trigram  to the playoffs 76) True)
  (= 
    (trigram  to find out 76) True)
  (= 
    (trigram  the new ones 76) True)
  (= 
    (trigram  the death star 76) True)
  (= 
    (trigram  thats a really 76) True)
  (= 
    (trigram  star wars character 76) True)
  (= 
    (trigram  really like it 76) True)
  (= 
    (trigram  out to be 76) True)
  (= 
    (trigram  on the edge 76) True)
  (= 
    (trigram  ive heard that 76) True)
  (= 
    (trigram  it to be 76) True)
  (= 
    (trigram  its really good 76) True)
  (= 
    (trigram  it on the 76) True)
  (= 
    (trigram  it makes me 76) True)
  (= 
    (trigram  i think ill 76) True)
  (= 
    (trigram  i think his 76) True)
  (= 
    (trigram  is so much 76) True)
  (= 
    (trigram  is good but 76) True)
  (= 
    (trigram  i never heard 76) True)
  (= 
    (trigram  i mean the 76) True)
  (= 
    (trigram  i also really 76) True)
  (= 
    (trigram  havent seen that 76) True)
  (= 
    (trigram  going to get 76) True)
  (= 
    (trigram  but its a 76) True)
  (= 
    (trigram  but i liked 76) True)
  (= 
    (trigram  any of their 76) True)
  (= 
    (trigram  and of course 76) True)
  (= 
    (trigram  and listen to 76) True)
  (= 
    (trigram  yeah they have 75) True)
  (= 
    (trigram  yeah i remember 75) True)
  (= 
    (trigram  yeah i liked 75) True)
  (= 
    (trigram  yeah but the 75) True)
  (= 
    (trigram  who are the 75) True)
  (= 
    (trigram  'which,one,is' your favorite 75) True)
  (= 
    (trigram  they were all 75) True)
  (= 
    (trigram  the part where 75) True)
  (= 
    (trigram  now that you 75) True)
  (= 
    (trigram  not really but 75) True)
  (= 
    (trigram  not a huge 75) True)
  (= 
    (trigram  movie do you 75) True)
  (= 
    (trigram  it was funny 75) True)
  (= 
    (trigram  it that way 75) True)
  (= 
    (trigram  its a really 75) True)
  (= 
    (trigram  in a long 75) True)
  (= 
    (trigram  i guess its 75) True)
  (= 
    (trigram  i dont 'know,if,i' 75) True)
  (= 
    (trigram  'i,dont,know' if i 75) True)
  (= 
    (trigram  i didnt realize 75) True)
  (= 
    (trigram  i agree that 75) True)
  (= 
    (trigram  hey do you 75) True)
  (= 
    (trigram  he was pretty 75) True)
  (= 
    (trigram  he is really 75) True)
  (= 
    (trigram  forward to the 75) True)
  (= 
    (trigram  but its not 75) True)
  (= 
    (trigram  but i didnt 75) True)
  (= 
    (trigram  be one of 75) True)
  (= 
    (trigram  be interesting to 75) True)
  (= 
    (trigram  you know any 74) True)
  (= 
    (trigram  you dont think 74) True)
  (= 
    (trigram  yes they did 74) True)
  (= 
    (trigram  yes he does 74) True)
  (= 
    (trigram  yeah its a 74) True)
  (= 
    (trigram  was it about 74) True)
  (= 
    (trigram  to some of 74) True)
  (= 
    (trigram  the hall of 74) True)
  (= 
    (trigram  the best movie 74) True)
  (= 
    (trigram  should listen to 74) True)
  (= 
    (trigram  of music is 74) True)
  (= 
    (trigram  it was more 74) True)
  (= 
    (trigram  it is just 74) True)
  (= 
    (trigram  in the game 74) True)
  (= 
    (trigram  i just hope 74) True)
  (= 
    (trigram  i did see 74) True)
  (= 
    (trigram  i didnt even 74) True)
  (= 
    (trigram  i believe so 74) True)
  (= 
    (trigram  he was really 74) True)
  (= 
    (trigram  he is good 74) True)
  (= 
    (trigram  good to me 74) True)
  (= 
    (trigram  give them a 74) True)
  (= 
    (trigram  do with the 74) True)
  (= 
    (trigram  do they play 74) True)
  (= 
    (trigram  dont really like 74) True)
  (= 
    (trigram  did you go 74) True)
  (= 
    (trigram  didnt like it 74) True)
  (= 
    (trigram  black and white 74) True)
  (= 
    (trigram  because it is 74) True)
  (= 
    (trigram  a super bowl 74) True)
  (= 
    (trigram  agree to disagree 74) True)
  (= 
    (trigram  your thoughts on 73) True)
  (= 
    (trigram  you like best 73) True)
  (= 
    (trigram  yeah but he 73) True)
  (= 
    (trigram  who were the 73) True)
  (= 
    (trigram  who directed it 73) True)
  (= 
    (trigram  went to see 73) True)
  (= 
    (trigram  well you know 73) True)
  (= 
    (trigram  well i like 73) True)
  (= 
    (trigram  was a very 73) True)
  (= 
    (trigram  to watch that 73) True)
  (= 
    (trigram  to be on 73) True)
  (= 
    (trigram  they are making 73) True)
  (= 
    (trigram  the whole thing 73) True)
  (= 
    (trigram  the patriots are 73) True)
  (= 
    (trigram  that it is 73) True)
  (= 
    (trigram  not sure what 73) True)
  (= 
    (trigram  music from the 73) True)
  (= 
    (trigram  loved that movie 73) True)
  (= 
    (trigram  like any of 73) True)
  (= 
    (trigram  i will see 73) True)
  (= 
    (trigram  its really good 73) True)
  (= 
    (trigram  in the original 73) True)
  (= 
    (trigram  im looking forward 73) True)
  (= 
    (trigram  'i,like,that' one too 73) True)
  (= 
    (trigram  he would have 73) True)
  (= 
    (trigram  heard about that 73) True)
  (= 
    (trigram  go with the 73) True)
  (= 
    (trigram  favorite type of 73) True)
  (= 
    (trigram  favorite character in 73) True)
  (= 
    (trigram  ever listened to 73) True)
  (= 
    (trigram  dont think that 73) True)
  (= 
    (trigram  dont know that 73) True)
  (= 
    (trigram  but not as 73) True)
  (= 
    (trigram  but i heard 73) True)
  (= 
    (trigram  but i did 73) True)
  (= 
    (trigram  both of those 73) True)
  (= 
    (trigram  are pretty good 73) True)
  (= 
    (trigram  and they have 73) True)
  (= 
    (trigram  a little too 73) True)
  (= 
    (trigram  yeah thats right 72) True)
  (= 
    (trigram  yeah i would 72) True)
  (= 
    (trigram  yeah but they 72) True)
  (= 
    (trigram  would it be 72) True)
  (= 
    (trigram  what was that 72) True)
  (= 
    (trigram  well i have 72) True)
  (= 
    (trigram  was the one 72) True)
  (= 
    (trigram  was it good 72) True)
  (= 
    (trigram  was better than 72) True)
  (= 
    (trigram  the nfl season 72) True)
  (= 
    (trigram  song by them 72) True)
  (= 
    (trigram  some kind of 72) True)
  (= 
    (trigram  see that one 72) True)
  (= 
    (trigram  one with the 72) True)
  (= 
    (trigram  oh man i 72) True)
  (= 
    (trigram  oh for sure 72) True)
  (= 
    (trigram  no not yet 72) True)
  (= 
    (trigram  might be the 72) True)
  (= 
    (trigram  little bit of 72) True)
  (= 
    (trigram  liked that one 72) True)
  (= 
    (trigram  know how to 72) True)
  (= 
    (trigram  i would probably 72) True)
  (= 
    (trigram  its such a 72) True)
  (= 
    (trigram  it is good 72) True)
  (= 
    (trigram  it come out 72) True)
  (= 
    (trigram  it as well 72) True)
  (= 
    (trigram  is so funny 72) True)
  (= 
    (trigram  i saw him 72) True)
  (= 
    (trigram  i mean it 72) True)
  (= 
    (trigram  i do but 72) True)
  (= 
    (trigram  i cant stand 72) True)
  (= 
    (trigram  i always liked 72) True)
  (= 
    (trigram  i agree and 72) True)
  (= 
    (trigram  dont know what 72) True)
  (= 
    (trigram  all over the 72) True)
  (= 
    (trigram  a horror movie 72) True)
  (= 
    (trigram  your favorite pop 71) True)
  (= 
    (trigram  you get to 71) True)
  (= 
    (trigram  yeah i have 71) True)
  (= 
    (trigram  wow that sounds 71) True)
  (= 
    (trigram  with you there 71) True)
  (= 
    (trigram  who are you 71) True)
  (= 
    (trigram  when they are 71) True)
  (= 
    (trigram  what songs do 71) True)
  (= 
    (trigram  were in the 71) True)
  (= 
    (trigram  went to a 71) True)
  (= 
    (trigram  to think of 71) True)
  (= 
    (trigram  the live action 71) True)
  (= 
    (trigram  the beginning of 71) True)
  (= 
    (trigram  so did i 71) True)
  (= 
    (trigram  over the top 71) True)
  (= 
    (trigram  oh yes i 71) True)
  (= 
    (trigram  no not yet 71) True)
  (= 
    (trigram  need to get 71) True)
  (= 
    (trigram  like the first 71) True)
  (= 
    (trigram  like it was 71) True)
  (= 
    (trigram  just have to 71) True)
  (= 
    (trigram  ive seen it 71) True)
  (= 
    (trigram  it was that 71) True)
  (= 
    (trigram  it as well 71) True)
  (= 
    (trigram  i still like 71) True)
  (= 
    (trigram  is not a 71) True)
  (= 
    (trigram  in the 90s 71) True)
  (= 
    (trigram  in it too 71) True)
  (= 
    (trigram  if you could 71) True)
  (= 
    (trigram  'i,did,not' know that 71) True)
  (= 
    (trigram  i agree he 71) True)
  (= 
    (trigram  he was good 71) True)
  (= 
    (trigram  heard that song 71) True)
  (= 
    (trigram  have never seen 71) True)
  (= 
    (trigram  got to see 71) True)
  (= 
    (trigram  favorite part of 71) True)
  (= 
    (trigram  dont have a 71) True)
  (= 
    (trigram  check that out 71) True)
  (= 
    (trigram  check out the 71) True)
  (= 
    (trigram  but my favorite 71) True)
  (= 
    (trigram  at this point 71) True)
  (= 
    (trigram  as the first 71) True)
  (= 
    (trigram  any of his 71) True)
  (= 
    (trigram  and i really 71) True)
  (= 
    (trigram  and i like 71) True)
  (= 
    (trigram  your favorite nfl 70) True)
  (= 
    (trigram  your favorite comedy 70) True)
  (= 
    (trigram  you know that 70) True)
  (= 
    (trigram  you heard any 70) True)
  (= 
    (trigram  you dont have 70) True)
  (= 
    (trigram  yes i would 70) True)
  (= 
    (trigram  yeah i did 70) True)
  (= 
    (trigram  wow thats a 70) True)
  (= 
    (trigram  'why,do,you' think that 70) True)
  (= 
    (trigram  whats it called 70) True)
  (= 
    (trigram  what makes it 70) True)
  (= 
    (trigram  what are they 70) True)
  (= 
    (trigram  trying to get 70) True)
  (= 
    (trigram  to check out 70) True)
  (= 
    (trigram  they were in 70) True)
  (= 
    (trigram  they seem to 70) True)
  (= 
    (trigram  the voice of 70) True)
  (= 
    (trigram  there any other 70) True)
  (= 
    (trigram  the live action 70) True)
  (= 
    (trigram  that they were 70) True)
  (= 
    (trigram  that sounds really 70) True)
  (= 
    (trigram  that song too 70) True)
  (= 
    (trigram  that i have 70) True)
  (= 
    (trigram  team do you 70) True)
  (= 
    (trigram  see your point 70) True)
  (= 
    (trigram  scene in the 70) True)
  (= 
    (trigram  never thought of 70) True)
  (= 
    (trigram  mean by that 70) True)
  (= 
    (trigram  know he was 70) True)
  (= 
    (trigram  i would not 70) True)
  (= 
    (trigram  it so much 70) True)
  (= 
    (trigram  it all the 70) True)
  (= 
    (trigram  i still dont 70) True)
  (= 
    (trigram  i read that 70) True)
  (= 
    (trigram  in a movie 70) True)
  (= 
    (trigram  i mean the 70) True)
  (= 
    (trigram  his music is 70) True)
  (= 
    (trigram  hes going to 70) True)
  (= 
    (trigram  have a few 70) True)
  (= 
    (trigram  dont think the 70) True)
  (= 
    (trigram  cant wait for 70) True)
  (= 
    (trigram  born this way 70) True)
  (= 
    (trigram  a song called 70) True)
  (= 
    (trigram  a really great 70) True)
  (= 
    (trigram  you say is 69) True)
  (= 
    (trigram  you know when 69) True)
  (= 
    (trigram  you didnt like 69) True)
  (= 
    (trigram  with a new 69) True)
  (= 
    (trigram  what a great 69) True)
  (= 
    (trigram  was pretty cool 69) True)
  (= 
    (trigram  was able to 69) True)
  (= 
    (trigram  want to talk 69) True)
  (= 
    (trigram  to get the 69) True)
  (= 
    (trigram  they do have 69) True)
  (= 
    (trigram  the way the 69) True)
  (= 
    (trigram  the next movie 69) True)
  (= 
    (trigram  the lyrics are 69) True)
  (= 
    (trigram  that sounds really 69) True)
  (= 
    (trigram  that is pretty 69) True)
  (= 
    (trigram  that in the 69) True)
  (= 
    (trigram  still listen to 69) True)
  (= 
    (trigram  probably my favorite 69) True)
  (= 
    (trigram  of the nfl 69) True)
  (= 
    (trigram  no it was 69) True)
  (= 
    (trigram  many of the 69) True)
  (= 
    (trigram  like pop music 69) True)
  (= 
    (trigram  know i think 69) True)
  (= 
    (trigram  i liked him 69) True)
  (= 
    (trigram  i guess its 69) True)
  (= 
    (trigram  i get it 69) True)
  (= 
    (trigram  if you are 69) True)
  (= 
    (trigram  if it was 69) True)
  (= 
    (trigram  i dont 'know,about,that' 69) True)
  (= 
    (trigram  'i,dont,know' about that 69) True)
  (= 
    (trigram  he is not 69) True)
  (= 
    (trigram  'have,you,heard' the new 69) True)
  (= 
    (trigram  have to give 69) True)
  (= 
    (trigram  have so many 69) True)
  (= 
    (trigram  has such a 69) True)
  (= 
    (trigram  for the nfl 69) True)
  (= 
    (trigram  feel about the 69) True)
  (= 
    (trigram  could see that 69) True)
  (= 
    (trigram  can see why 69) True)
  (= 
    (trigram  but i thought 69) True)
  (= 
    (trigram  and i loved 69) True)
  (= 
    (trigram  again this year 69) True)
  (= 
    (trigram  a few times 69) True)
  (= 
    (trigram  a few songs 69) True)
  (= 
    (trigram  you think its 68) True)
  (= 
    (trigram  you looking forward 68) True)
  (= 
    (trigram  you are a 68) True)
  (= 
    (trigram  yeah i was 68) True)
  (= 
    (trigram  yeah i saw 68) True)
  (= 
    (trigram  yeah i just 68) True)
  (= 
    (trigram  would be nice 68) True)
  (= 
    (trigram  when you were 68) True)
  (= 
    (trigram  whats it called 68) True)
  (= 
    (trigram  what do they 68) True)
  (= 
    (trigram  well if you 68) True)
  (= 
    (trigram  used to listen 68) True)
  (= 
    (trigram  the world series 68) True)
  (= 
    (trigram  the new york 68) True)
  (= 
    (trigram  the most recent 68) True)
  (= 
    (trigram  the hall of 68) True)
  (= 
    (trigram  'that,was,a' good one 68) True)
  (= 
    (trigram  song on the 68) True)
  (= 
    (trigram  so i think 68) True)
  (= 
    (trigram  see a movie 68) True)
  (= 
    (trigram  one in the 68) True)
  (= 
    (trigram  one but i 68) True)
  (= 
    (trigram  of them but 68) True)
  (= 
    (trigram  like the old 68) True)
  (= 
    (trigram  i would agree 68) True)
  (= 
    (trigram  i will definitely 68) True)
  (= 
    (trigram  i thought you 68) True)
  (= 
    (trigram  is it good 68) True)
  (= 
    (trigram  is it called 68) True)
  (= 
    (trigram  in the early 68) True)
  (= 
    (trigram  in the beginning 68) True)
  (= 
    (trigram  i know she 68) True)
  (= 
    (trigram  i just like 68) True)
  (= 
    (trigram  i just cant 68) True)
  (= 
    (trigram  i have always 68) True)
  (= 
    (trigram  i am excited 68) True)
  (= 
    (trigram  hey are you 68) True)
  (= 
    (trigram  have the best 68) True)
  (= 
    (trigram  have seen that 68) True)
  (= 
    (trigram  going to make 68) True)
  (= 
    (trigram  go back to 68) True)
  (= 
    (trigram  dont get me 68) True)
  (= 
    (trigram  do not like 68) True)
  (= 
    (trigram  'did,you,ever' see the 68) True)
  (= 
    (trigram  but not the 68) True)
  (= 
    (trigram  and a lot 68) True)
  (= 
    (trigram  about that movie 68) True)
  (= 
    (trigram  you seen that 67) True)
  (= 
    (trigram  yes and i 67) True)
  (= 
    (trigram  yeah i am 67) True)
  (= 
    (trigram  yeah but it 67) True)
  (= 
    (trigram  why would you 67) True)
  (= 
    (trigram  who are some 67) True)
  (= 
    (trigram  where do you 67) True)
  (= 
    (trigram  well i am 67) True)
  (= 
    (trigram  up to the 67) True)
  (= 
    (trigram  to think about 67) True)
  (= 
    (trigram  think there are 67) True)
  (= 
    (trigram  think he has 67) True)
  (= 
    (trigram  theyre going to 67) True)
  (= 
    (trigram  the third one 67) True)
  (= 
    (trigram  the best one 67) True)
  (= 
    (trigram  that they have 67) True)
  (= 
    (trigram  that should be 67) True)
  (= 
    (trigram  so who is 67) True)
  (= 
    (trigram  so much better 67) True)
  (= 
    (trigram  seen all of 67) True)
  (= 
    (trigram  ok thank you 67) True)
  (= 
    (trigram  oh wow i 67) True)
  (= 
    (trigram  oh i remember 67) True)
  (= 
    (trigram  nice talking to 67) True)
  (= 
    (trigram  just came out 67) True)
  (= 
    (trigram  jar jar binks 67) True)
  (= 
    (trigram  ive seen that 67) True)
  (= 
    (trigram  it that way 67) True)
  (= 
    (trigram  is on the 67) True)
  (= 
    (trigram  is a pretty 67) True)
  (= 
    (trigram  i prefer the 67) True)
  (= 
    (trigram  in the future 67) True)
  (= 
    (trigram  im not really 67) True)
  (= 
    (trigram  i loved her 67) True)
  (= 
    (trigram  i cant imagine 67) True)
  (= 
    (trigram  he has to 67) True)
  (= 
    (trigram  heard that too 67) True)
  (= 
    (trigram  for the recommendation 67) True)
  (= 
    (trigram  yeah i did 66) True)
  (= 
    (trigram  yeah i cant 66) True)
  (= 
    (trigram  would you want 66) True)
  (= 
    (trigram  'who,do,you' 'think,is,the' best 66) True)
  (= 
    (trigram  what song do 66) True)
  (= 
    (trigram  what i think 66) True)
  (= 
    (trigram  what have you 66) True)
  (= 
    (trigram  well they are 66) True)
  (= 
    (trigram  well in the 66) True)
  (= 
    (trigram  used to play 66) True)
  (= 
    (trigram  think will be 66) True)
  (= 
    (trigram  they were pretty 66) True)
  (= 
    (trigram  they are one 66) True)
  (= 
    (trigram  there were some 66) True)
  (= 
    (trigram  the dallas cowboys 66) True)
  (= 
    (trigram  thats a classic 66) True)
  (= 
    (trigram  so it was 66) True)
  (= 
    (trigram  okay i will 66) True)
  (= 
    (trigram  oh yeah thats 66) True)
  (= 
    (trigram  oh i like 66) True)
  (= 
    (trigram  listening to it 66) True)
  (= 
    (trigram  like the way 66) True)
  (= 
    (trigram  it when it 66) True)
  (= 
    (trigram  its not a 66) True)
  (= 
    (trigram  its a good 66) True)
  (= 
    (trigram  i tend to 66) True)
  (= 
    (trigram  is what i 66) True)
  (= 
    (trigram  i remember seeing 66) True)
  (= 
    (trigram  i didnt really 66) True)
  (= 
    (trigram  he was just 66) True)
  (= 
    (trigram  have to wait 66) True)
  (= 
    (trigram  get a chance 66) True)
  (= 
    (trigram  dont you like 66) True)
  (= 
    (trigram  does have a 66) True)
  (= 
    (trigram  cant think of 66) True)
  (= 
    (trigram  a movie that 66) True)
  (= 
    (trigram  am a big 66) True)
  (= 
    (trigram  a lot better 66) True)
  (= 
    (trigram  a great band 66) True)
  (= 
    (trigram  a good choice 66) True)
  (= 
    (trigram  you tell me 65) True)
  (= 
    (trigram  you ever listened 65) True)
  (= 
    (trigram  yes they do 65) True)
  (= 
    (trigram  yeah thats right 65) True)
  (= 
    (trigram  what i think 65) True)
  (= 
    (trigram  what are the 65) True)
  (= 
    (trigram  was thinking about 65) True)
  (= 
    (trigram  to watch them 65) True)
  (= 
    (trigram  think they should 65) True)
  (= 
    (trigram  think i saw 65) True)
  (= 
    (trigram  the nfl is 65) True)
  (= 
    (trigram  the first two 65) True)
  (= 
    (trigram  the disney movie 65) True)
  (= 
    (trigram  the bad guy 65) True)
  (= 
    (trigram  that was great 65) True)
  (= 
    (trigram  that must have 65) True)
  (= 
    (trigram  so whats your 65) True)
  (= 
    (trigram  so are you 65) True)
  (= 
    (trigram  one in the 65) True)
  (= 
    (trigram  of star wars 65) True)
  (= 
    (trigram  not my favorite 65) True)
  (= 
    (trigram  no i did 65) True)
  (= 
    (trigram  like star wars 65) True)
  (= 
    (trigram  liked the first 65) True)
  (= 
    (trigram  just as good 65) True)
  (= 
    (trigram  i think their 65) True)
  (= 
    (trigram  is the only 65) True)
  (= 
    (trigram  is it any 65) True)
  (= 
    (trigram  i mean it 65) True)
  (= 
    (trigram  i like when 65) True)
  (= 
    (trigram  if i can 65) True)
  (= 
    (trigram  i didnt think 65) True)
  (= 
    (trigram  i can agree 65) True)
  (= 
    (trigram  i bet they 65) True)
  (= 
    (trigram  i agree and 65) True)
  (= 
    (trigram  he was just 65) True)
  (= 
    (trigram  have the same 65) True)
  (= 
    (trigram  have not heard 65) True)
  (= 
    (trigram  have a new 65) True)
  (= 
    (trigram  go see the 65) True)
  (= 
    (trigram  give you that 65) True)
  (= 
    (trigram  dont listen to 65) True)
  (= 
    (trigram  dont know i 65) True)
  (= 
    (trigram  as the original 65) True)
  (= 
    (trigram  a great team 65) True)
  (= 
    (trigram  you seen it 64) True)
  (= 
    (trigram  you really should 64) True)
  (= 
    (trigram  you like lady 64) True)
  (= 
    (trigram  you for the 64) True)
  (= 
    (trigram  yes she was 64) True)
  (= 
    (trigram  yeah i cant 64) True)
  (= 
    (trigram  will do this 64) True)
  (= 
    (trigram  well in the 64) True)
  (= 
    (trigram  watch the movie 64) True)
  (= 
    (trigram  to play the 64) True)
  (= 
    (trigram  too but i 64) True)
  (= 
    (trigram  to check that 64) True)
  (= 
    (trigram  to be good 64) True)
  (= 
    (trigram  to agree with 64) True)
  (= 
    (trigram  thought so too 64) True)
  (= 
    (trigram  they were in 64) True)
  (= 
    (trigram  they were great 64) True)
  (= 
    (trigram  the main characters 64) True)
  (= 
    (trigram  thats kind of 64) True)
  (= 
    (trigram  thats a hard 64) True)
  (= 
    (trigram  so much fun 64) True)
  (= 
    (trigram  so i think 64) True)
  (= 
    (trigram  so i guess 64) True)
  (= 
    (trigram  so are you 64) True)
  (= 
    (trigram  since i was 64) True)
  (= 
    (trigram  see him in 64) True)
  (= 
    (trigram  oh you mean 64) True)
  (= 
    (trigram  of the old 64) True)
  (= 
    (trigram  not sure about 64) True)
  (= 
    (trigram  lot of them 64) True)
  (= 
    (trigram  let me guess 64) True)
  (= 
    (trigram  it is but 64) True)
  (= 
    (trigram  is the movie 64) True)
  (= 
    (trigram  is an amazing 64) True)
  (= 
    (trigram  is also a 64) True)
  (= 
    (trigram  i miss the 64) True)
  (= 
    (trigram  i just got 64) True)
  (= 
    (trigram  i cant 'wait,for,the' 64) True)
  (= 
    (trigram  'i,cant,wait' for the 64) True)
  (= 
    (trigram  i agree that 64) True)
  (= 
    (trigram  did you catch 64) True)
  (= 
    (trigram  coming out with 64) True)
  (= 
    (trigram  cant wait to 64) True)
  (= 
    (trigram  but you know 64) True)
  (= 
    (trigram  but i can 64) True)
  (= 
    (trigram  be a lot 64) True)
  (= 
    (trigram  based on the 64) True)
  (= 
    (trigram  are talking about 64) True)
  (= 
    (trigram  a good thing 64) True)
  (= 
    (trigram  you seen all 63) True)
  (= 
    (trigram  yes they have 63) True)
  (= 
    (trigram  yeah youre right 63) True)
  (= 
    (trigram  wonder woman movie 63) True)
  (= 
    (trigram  whos in it 63) True)
  (= 
    (trigram  when i saw 63) True)
  (= 
    (trigram  what other movies 63) True)
  (= 
    (trigram  'what,are,your' thoughts on 63) True)
  (= 
    (trigram  well i really 63) True)
  (= 
    (trigram  was a huge 63) True)
  (= 
    (trigram  to hear that 63) True)
  (= 
    (trigram  to get to 63) True)
  (= 
    (trigram  this one is 63) True)
  (= 
    (trigram  this is true 63) True)
  (= 
    (trigram  they should be 63) True)
  (= 
    (trigram  they had some 63) True)
  (= 
    (trigram  the one about 63) True)
  (= 
    (trigram  the dallas cowboys 63) True)
  (= 
    (trigram  the best team 63) True)
  (= 
    (trigram  that is my 63) True)
  (= 
    (trigram  she had a 63) True)
  (= 
    (trigram  part of it 63) True)
  (= 
    (trigram  oh that was 63) True)
  (= 
    (trigram  my favorite team 63) True)
  (= 
    (trigram  like they are 63) True)
  (= 
    (trigram  ive seen it 63) True)
  (= 
    (trigram  is probably the 63) True)
  (= 
    (trigram  in the superbowl 63) True)
  (= 
    (trigram  in the middle 63) True)
  (= 
    (trigram  in it too 63) True)
  (= 
    (trigram  i never really 63) True)
  (= 
    (trigram  in all of 63) True)
  (= 
    (trigram  im a fan 63) True)
  (= 
    (trigram  ill give you 63) True)
  (= 
    (trigram  i just cant 63) True)
  (= 
    (trigram  i hear that 63) True)
  (= 
    (trigram  have to get 63) True)
  (= 
    (trigram  for some reason 63) True)
  (= 
    (trigram  dont think the 63) True)
  (= 
    (trigram  be honest i 63) True)
  (= 
    (trigram  because he was 63) True)
  (= 
    (trigram  a part of 63) True)
  (= 
    (trigram  and i am 63) True)
  (= 
    (trigram  am not a 63) True)
  (= 
    (trigram  a great album 63) True)
  (= 
    (trigram  your favorite type 62) True)
  (= 
    (trigram  your favorite songs 62) True)
  (= 
    (trigram  your favorite music 62) True)
  (= 
    (trigram  your favorite artist 62) True)
  (= 
    (trigram  you like her 62) True)
  (= 
    (trigram  you know he 62) True)
  (= 
    (trigram  would be fun 62) True)
  (= 
    (trigram  with a lot 62) True)
  (= 
    (trigram  when was the 62) True)
  (= 
    (trigram  what it is 62) True)
  (= 
    (trigram  what else do 62) True)
  (= 
    (trigram  well he was 62) True)
  (= 
    (trigram  was that the 62) True)
  (= 
    (trigram  was in a 62) True)
  (= 
    (trigram  want to know 62) True)
  (= 
    (trigram  to the beatles 62) True)
  (= 
    (trigram  think was the 62) True)
  (= 
    (trigram  think the patriots 62) True)
  (= 
    (trigram  they still have 62) True)
  (= 
    (trigram  they dont have 62) True)
  (= 
    (trigram  the whole time 62) True)
  (= 
    (trigram  the story of 62) True)
  (= 
    (trigram  so who do 62) True)
  (= 
    (trigram  seen that movie 62) True)
  (= 
    (trigram  on the team 62) True)
  (= 
    (trigram  no it is 62) True)
  (= 
    (trigram  maybe we can 62) True)
  (= 
    (trigram  lot of movies 62) True)
  (= 
    (trigram  lot of his 62) True)
  (= 
    (trigram  listen to her 62) True)
  (= 
    (trigram  like the best 62) True)
  (= 
    (trigram  know that song 62) True)
  (= 
    (trigram  its just a 62) True)
  (= 
    (trigram  its been a 62) True)
  (= 
    (trigram  is in that 62) True)
  (= 
    (trigram  in the star 62) True)
  (= 
    (trigram  in the second 62) True)
  (= 
    (trigram  i know she 62) True)
  (= 
    (trigram  i hope you 62) True)
  (= 
    (trigram  i guess but 62) True)
  (= 
    (trigram  i dont get 62) True)
  (= 
    (trigram  i agree the 62) True)
  (= 
    (trigram  how is it 62) True)
  (= 
    (trigram  hey have you 62) True)
  (= 
    (trigram  her in the 62) True)
  (= 
    (trigram  heard the song 62) True)
  (= 
    (trigram  has always been 62) True)
  (= 
    (trigram  green bay packers 62) True)
  (= 
    (trigram  dont know why 62) True)
  (= 
    (trigram  does that mean 62) True)
  (= 
    (trigram  does he play 62) True)
  (= 
    (trigram  'did,you,see' the new 62) True)
  (= 
    (trigram  but they were 62) True)
  (= 
    (trigram  but its a 62) True)
  (= 
    (trigram  but i havent 62) True)
  (= 
    (trigram  been around for 62) True)
  (= 
    (trigram  are a good 62) True)
  (= 
    (trigram  a great player 62) True)
  (= 
    (trigram  your all time 61) True)
  (= 
    (trigram  you hear the 61) True)
  (= 
    (trigram  you heard about 61) True)
  (= 
    (trigram  yes i remember 61) True)
  (= 
    (trigram  yes i know 61) True)
  (= 
    (trigram  yeah youre right 61) True)
  (= 
    (trigram  yeah i loved 61) True)
  (= 
    (trigram  yeah i heard 61) True)
  (= 
    (trigram  yeah but its 61) True)
  (= 
    (trigram  wow i didnt 61) True)
  (= 
    (trigram  will do this 61) True)
  (= 
    (trigram  why i like 61) True)
  (= 
    (trigram  why dont you 61) True)
  (= 
    (trigram  why are you 61) True)
  (= 
    (trigram  well he is 61) True)
  (= 
    (trigram  was so sad 61) True)
  (= 
    (trigram  to the new 61) True)
  (= 
    (trigram  to see if 61) True)
  (= 
    (trigram  think a lot 61) True)
  (= 
    (trigram  'there,are,a' lot of 61) True)
  (= 
    (trigram  the movie with 61) True)
  (= 
    (trigram  the movie about 61) True)
  (= 
    (trigram  that one too 61) True)
  (= 
    (trigram  that is good 61) True)
  (= 
    (trigram  'that,is,a' great song 61) True)
  (= 
    (trigram  that i can 61) True)
  (= 
    (trigram  so did you 61) True)
  (= 
    (trigram  she did a 61) True)
  (= 
    (trigram  see the movie 61) True)
  (= 
    (trigram  see them in 61) True)
  (= 
    (trigram  saw that one 61) True)
  (= 
    (trigram  remember that song 61) True)
  (= 
    (trigram  ready for the 61) True)
  (= 
    (trigram  original star wars 61) True)
  (= 
    (trigram  of the team 61) True)
  (= 
    (trigram  of the same 61) True)
  (= 
    (trigram  not like the 61) True)
  (= 
    (trigram  never seen it 61) True)
  (= 
    (trigram  my favorite was 61) True)
  (= 
    (trigram  me know what 61) True)
  (= 
    (trigram  like the original 61) True)
  (= 
    (trigram  just want to 61) True)
  (= 
    (trigram  i will watch 61) True)
  (= 
    (trigram  i will do 61) True)
  (= 
    (trigram  it was cool 61) True)
  (= 
    (trigram  i think im 61) True)
  (= 
    (trigram  in the draft 61) True)
  (= 
    (trigram  im sure they 61) True)
  (= 
    (trigram  i hope it 61) True)
  (= 
    (trigram  if it is 61) True)
  (= 
    (trigram  i dont 'think,i,have' 61) True)
  (= 
    (trigram  'i,dont,think' i have 61) True)
  (= 
    (trigram  i do love 61) True)
  (= 
    (trigram  how was the 61) True)
  (= 
    (trigram  'how,do,you' think the 61) True)
  (= 
    (trigram  excited about the 61) True)
  (= 
    (trigram  did he do 61) True)
  (= 
    (trigram  can you name 61) True)
  (= 
    (trigram  can listen to 61) True)
  (= 
    (trigram  because they are 61) True)
  (= 
    (trigram  a star wars 61) True)
  (= 
    (trigram  and then the 61) True)
  (= 
    (trigram  a movie about 61) True)
  (= 
    (trigram  a lot but 61) True)

