/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index(goal_L_expansion(?,?,?), assert_db_Local, assert_db_local).
index(retractall_L_hp(?,?), assert_db_Local, assert_db_local).
index(retractall_L(?,?), assert_db_Local, assert_db_local).
index(retractall_L(?), assert_db_Local, assert_db_local).
index(retract_L_hp(?,?), assert_db_Local, assert_db_local).
index(retract_L(?,?), assert_db_Local, assert_db_local).
index(retract_L(?), assert_db_Local, assert_db_local).
index(into_hp_L(?,?), assert_db_Local, assert_db_local).
index(check_L(?), assert_db_Local, assert_db_local).
index(call_L(?), assert_db_Local, assert_db_local).
index(call_L(?,?), assert_db_Local, assert_db_local).
index(install_L, assert_db_Local, assert_db_local).
index(reset_L, assert_db_Local, assert_db_local).
index(last_cons(?,?), assert_db_Local, assert_db_local).
index(assertz_L_hp(?,?), assert_db_Local, assert_db_local).
index(assertz_L(?,?), assert_db_Local, assert_db_local).
index(assertz_L(?), assert_db_Local, assert_db_local).
index(assert_L(?,?), assert_db_Local, assert_db_local).
index(assert_L(?), assert_db_Local, assert_db_local).
index(asserta_L_hp(?,?), assert_db_Local, assert_db_local).
index(asserta_L(?,?), assert_db_Local, assert_db_local).
index(asserta_L(?), assert_db_Local, assert_db_local).
index(erase_L(?,?), assert_db_Local, assert_db_local).
index(clause_L(?,?,?,?), assert_db_Local, assert_db_local).
index(ref_L(?,?,?), assert_db_Local, assert_db_local).
index(clause_L(?,?,?), assert_db_Local, assert_db_local).
index(erase_L(?), assert_db_Local, assert_db_local).
index(show_L(?), assert_db_Local, assert_db_local).
index(listing_L(?), assert_db_Local, assert_db_local).
index(listing_L, assert_db_Local, assert_db_local).
index(was_dynamic_L(?,?), assert_db_Local, assert_db_local).
index(make_dynamic_L(?,?,?), assert_db_Local, assert_db_local).
index(dynamic_L(?), assert_db_Local, assert_db_local).
index(install_L, assert_db_Local, assert_db_local).
index(disable_L, assert_db_Local, assert_db_local).
index(enable_L, assert_db_Local, assert_db_local).
index(each_call_cleanup(?,?,?), ecc_legacy, each_call_cleanup).
index(get_file_from_stream(?,?), echo_files, echo_source_files).
index(assume_caughtup_to(?,?,?), echo_files, echo_source_files).
index(logicmoo_webbot, logicmoo_lib, logicmoo_lib).
index(setup_logicmoo_operators, logicmoo_lib, logicmoo_lib).
index(rescan_pack_autoload_packages, logicmoo_packages, logicmoo_packs).
index(test_pengines, logicmoo_remote, logicmoo_remote).
index(pengine_server, logicmoo_remote, logicmoo_remote).
index(define_into_module(:), logicmoo_startup, logicmoo_startup).
index(test_case_1, multivar, multivar).
index(test_case_2, multivar, multivar).
index(test_case_3, multivar, multivar).
index(test_case_4, multivar, multivar).
index(this_script_begin, script_files, script_files).
index(this_script_ends, script_files, script_files).
index(process_script_file, script_files, script_files).
index(process_script_file(?), script_files, script_files).
index(process_script_file(?,?), script_files, script_files).
index(process_stream(?), script_files, script_files).
index(visit_script_term(*), script_files, script_files).
index(xlisting(?), xlisting_lm, xlisting).
