/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index((goal_L_expansion), 3, assert_db_Local, assert_db_local).
index((retractall_L_hp), 2, assert_db_Local, assert_db_local).
index((retractall_L), 2, assert_db_Local, assert_db_local).
index((retractall_L), 1, assert_db_Local, assert_db_local).
index((retract_L_hp), 2, assert_db_Local, assert_db_local).
index((retract_L), 2, assert_db_Local, assert_db_local).
index((retract_L), 1, assert_db_Local, assert_db_local).
index((into_hp_L), 2, assert_db_Local, assert_db_local).
index((check_L), 1, assert_db_Local, assert_db_local).
index((call_L), 1, assert_db_Local, assert_db_local).
index((call_L), 2, assert_db_Local, assert_db_local).
index((install_L), 0, assert_db_Local, assert_db_local).
index((reset_L), 0, assert_db_Local, assert_db_local).
index((last_cons), 2, assert_db_Local, assert_db_local).
index((assertz_L_hp), 2, assert_db_Local, assert_db_local).
index((assertz_L), 2, assert_db_Local, assert_db_local).
index((assertz_L), 1, assert_db_Local, assert_db_local).
index((assert_L), 2, assert_db_Local, assert_db_local).
index((assert_L), 1, assert_db_Local, assert_db_local).
index((asserta_L_hp), 2, assert_db_Local, assert_db_local).
index((asserta_L), 2, assert_db_Local, assert_db_local).
index((asserta_L), 1, assert_db_Local, assert_db_local).
index((erase_L), 2, assert_db_Local, assert_db_local).
index((clause_L), 4, assert_db_Local, assert_db_local).
index((ref_L), 3, assert_db_Local, assert_db_local).
index((clause_L), 3, assert_db_Local, assert_db_local).
index((erase_L), 1, assert_db_Local, assert_db_local).
index((show_L), 1, assert_db_Local, assert_db_local).
index((listing_L), 1, assert_db_Local, assert_db_local).
index((listing_L), 0, assert_db_Local, assert_db_local).
index((was_dynamic_L), 2, assert_db_Local, assert_db_local).
index((make_dynamic_L), 3, assert_db_Local, assert_db_local).
index((dynamic_L), 1, assert_db_Local, assert_db_local).
index((install_L), 0, assert_db_Local, assert_db_local).
index((disable_L), 0, assert_db_Local, assert_db_local).
index((enable_L), 0, assert_db_Local, assert_db_local).
index((each_call_cleanup), 3, ecc_legacy, each_call_cleanup).
index((get_file_from_stream), 2, echo_files, echo_source_files).
index((assume_caughtup_to), 3, echo_files, echo_source_files).
index((logicmoo_webbot), 0, logicmoo_lib, logicmoo_lib).
index((setup_logicmoo_operators), 0, logicmoo_lib, logicmoo_lib).
index((rescan_pack_autoload_packages), 0, logicmoo_packages, logicmoo_packs).
index((test_pengines), 0, logicmoo_remote, logicmoo_remote).
index((pengine_server), 0, logicmoo_remote, logicmoo_remote).
index((define_into_module), 1, logicmoo_startup, logicmoo_startup).
index((test_case_1), 0, multivar, multivar).
index((test_case_2), 0, multivar, multivar).
index((test_case_3), 0, multivar, multivar).
index((test_case_4), 0, multivar, multivar).
index((mdwq), 1, multivar, multivar).
index((plvar), 1, multivar, multivar).
index((nb_var), 1, multivar, multivar).
index((nb_var), 2, multivar, multivar).
index((vdict), 1, multivar, multivar).
index((vdict), 2, multivar, multivar).
index((un_mv), 1, multivar, multivar).
index((un_mv1), 1, multivar, multivar).
index((mv_peek_value), 2, multivar, multivar).
index((mv_peek_value1), 2, multivar, multivar).
index((mv_set_values), 2, multivar, multivar).
index((mv_set1), 2, multivar, multivar).
index((mv_add1), 2, multivar, multivar).
index((mv_allow), 2, multivar, multivar).
index((ic_text), 1, multivar, multivar).
index((xvarx), 1, multivar, multivar).
index((is_mv), 1, multivar, multivar).
index((multivar), 1, multivar, multivar).
index((this_script_begin), 0, script_files, script_files).
index((this_script_ends), 0, script_files, script_files).
index((process_script_file), 0, script_files, script_files).
index((process_script_file), 1, script_files, script_files).
index((process_script_file), 2, script_files, script_files).
index((process_stream), 1, script_files, script_files).
index((visit_script_term), 1, script_files, script_files).
index((xlisting), 1, xlisting_lm, xlisting).

