bad1n
bad2n
bad3n
bad1rbad2rbad3rbad1nn

bad2nn

bad3nn

bad1nr
bad2nr
bad3nr
bad1rn
bad2rn
bad3rn
bad1rrbad2rrbad3rrbad1nnn


bad2nnn


bad3nnn


bad1nrn

bad2nrn

bad3nrn

bad1rnn

bad2rnn

bad3rnn

bad1rrn
bad2rrn
bad3rrn
bad1nnr

bad2nnr

bad3nnr

bad1nrr
bad2nrr
bad3nrr
bad1rnr
bad2rnr
bad3rnr
bad1rrrbad2rrrbad3rrr
now some tabs:one tab	twotab		threetab			end
