
:- discontiguous(lsp_hooks:handle_msg_hook/3).
:-     multifile(lsp_hooks:handle_msg_hook/3).
:-       dynamic(lsp_hooks:handle_msg_hook/3).
:- discontiguous(lsp_hooks:exec_code_action/3).
:-     multifile(lsp_hooks:exec_code_action/3).
:-       dynamic(lsp_hooks:exec_code_action/3).
:- discontiguous(lsp_hooks:compute_code_lens/3).
:-     multifile(lsp_hooks:compute_code_lens/3).
:-       dynamic(lsp_hooks:compute_code_lens/3).
:- discontiguous(lsp_hooks:compute_code_action/3).
:-     multifile(lsp_hooks:compute_code_action/3).
:-       dynamic(lsp_hooks:compute_code_action/3).
:- discontiguous(lsp_hooks:compute_each_code_lens/9).
:-     multifile(lsp_hooks:compute_each_code_lens/9).
:-       dynamic(lsp_hooks:compute_each_code_lens/9).
:- discontiguous(lsp_hooks:compute_typed_code_action/5).
:-     multifile(lsp_hooks:compute_typed_code_action/5).
:-       dynamic(lsp_hooks:compute_typed_code_action/5).
:- discontiguous(lsp_hooks:handle_save_actions/3).
:-     multifile(lsp_hooks:handle_save_actions/3).
:-       dynamic(lsp_hooks:handle_save_actions/3).
:- discontiguous(lsp_hooks:hover_string/5).
:-     multifile(lsp_hooks:hover_string/5).
:-       dynamic(lsp_hooks:hover_string/5).
:- discontiguous(lsp_hooks:hover_print/4).
:-     multifile(lsp_hooks:hover_print/4).
:-       dynamic(lsp_hooks:hover_print/4).
:- discontiguous(user:metta_file_buffer/7).
:-     multifile(user:metta_file_buffer/7).
:-       dynamic(user:metta_file_buffer/7).

